### ISSUE TITLE
Incorrect syntax error when trying to Provide script

### ISSUE THREAD

**Issue by kimtuitoek** [espertechinc/esper#101]
I need some help. Trying to follow the example from the documentation in [Chapter 5.14.7. Providing the Script](http://esper.espertech.com/release-6.1.0/esper-reference/html_single/index.html#joining_method_script), I've experiencing problems while trying to run the code in an epl file. 

Here is the code I tried to run:
```
create schema ItemEvent(
    id string
);

create window ItemEventWindow#lastevent as ItemEvent;

create expression EventBean[] @type(ItemEvent) js:myItemProducerScript() [
myItemProducerScript()
function myItemProducerScript() {
  var EventBeanArray = Java.type("com.espertech.esper.client.EventBean[]");
  var events = new EventBeanArray(1);
  events[0] = epl.getEventBeanService().adapterForMap(java.util.Collections.singletonMap("id", "id1"), "ItemEvent");

  return events;

select id from ItemEvent, method:myItemProducerScript();
}];
```
This is the error I got:
```Compilation failed in expression 'create expression EventBean[] @type(ItemEvent) js:...(206 chars)' : Incorrect syntax near 'myItemProducerScript' [create expression EventBean[] @type(ItemEvent) js:myItemProducerScript() [
myItemProducerScript()
function myItemProducerScript() {
  var EventBeanArray = Java.type("com.espertech.esper.client.EventBean[]")]
	...
Caused by: com.espertech.esper.client.deploy.DeploymentItemException: Incorrect syntax near 'myItemProducerScript' [create expression EventBean[] @type(ItemEvent) js:myItemProducerScript() [
myItemProducerScript()
function myItemProducerScript() {
  var EventBeanArray = Java.type("com.espertech.esper.client.EventBean[]")]
	at com.espertech.esper.core.deploy.EPDeploymentAdminImpl.deployInternalLockTaken(EPDeploymentAdminImpl.java:143)
	... 6 more
Caused by: com.espertech.esper.client.EPStatementSyntaxException: Incorrect syntax near 'myItemProducerScript' [create expression EventBean[] @type(ItemEvent) js:myItemProducerScript() [
myItemProducerScript()
function myItemProducerScript() {
  var EventBeanArray = Java.type("com.espertech.esper.client.EventBean[]")]
	at com.espertech.esper.epl.parse.ExceptionConvertor.convertStatement(ExceptionConvertor.java:46)
	at com.espertech.esper.epl.parse.ParseHelper.parse(ParseHelper.java:119)
	at com.espertech.esper.epl.parse.ParseHelper.handleScriptRewrite(ParseHelper.java:149)
	at com.espertech.esper.epl.parse.ParseHelper.parse(ParseHelper.java:117)
	at com.espertech.esper.core.service.EPAdministratorHelper.compileEPL(EPAdministratorHelper.java:86)
	at com.espertech.esper.core.service.EPAdministratorHelper.compileEPL(EPAdministratorHelper.java:68)
	at com.espertech.esper.core.service.EPAdministratorImpl.compileEPL(EPAdministratorImpl.java:192)
	at com.espertech.esper.core.deploy.EPDeploymentAdminImpl.deployInternalLockTaken(EPDeploymentAdminImpl.java:141)
	... 6 more
```

This is due to an incorrect syntax error despite following the example in the documentation. The regression tests in the esper github repo all pass including the one with the above example. I can't really tell why there is a syntax error at **EventBean[] @type(ItemEvent).**

**Comment by bernhardttom** [comment]
merged to master
