### ISSUE TITLE
Failed to Compile (Location not found)

### ISSUE THREAD

**Issue by kenwdelong** [espertechinc/esper#113]
When using 7.0 and 7.1, I am getting this error at startup:

```
2018-03-27 09:31:36.849 WARN  [main                 ] [com.espertech.esper.epl.expression.codegen.ExprNodeCompiler] [] [] Failed to code-generate for statement 'stmt_1' expression '(count(*))>=30' requestor-class 'ResultSetProcessorRowForAllForge' (invalid code follows, falling back to regular evaluation): Failed to compile generated code
code-in-error (please provide with issue reports):
   1  package com.espertech.esper.generated.uri_default;
   2  import com.espertech.esper.epl.expression.core.ExprEvaluatorContext;
   3  import com.espertech.esper.epl.expression.core.ExprEvaluator;
   4  import com.espertech.esper.client.EventBean;
   5  import com.espertech.esper.epl.expression.methodagg.ExprCountNode;
   6  public class ExprEvaluator_c8226d9ea4b6e4aedbdc5d1c10699001b implements ExprEvaluator {
   7    final ExprCountNode mb0;
   8
   9    public ExprEvaluator_c8226d9ea4b6e4aedbdc5d1c10699001b(ExprCountNode p0){
  10      this.mb0=p0;
  11    }
  12
  13    // ExprNodeCompiler
  14    public Object evaluate(EventBean[] eventsPerStream,boolean isNewData,ExprEvaluatorContext exprEvalCtx){
  15      return m0(eventsPerStream,exprEvalCtx,isNewData);
  16    }
  17
  18    // ExprRelationalOpNodeForgeEval
  19    Boolean m0(EventBean[] eventsPerStream,ExprEvaluatorContext exprEvalCtx,boolean isNewData){
  20      Long left=((Long)(mb0).evaluate(eventsPerStream,isNewData,exprEvalCtx));
  21      if (left == null) {return null;}
  22      int right=30;
  23      return (left>=((long)right));
  24    }
  25  }

com.espertech.esper.codegen.compile.CodegenCompilerException: Failed to compile generated code
        at com.espertech.esper.codegen.compile.CodegenCompilerJanino.compileClass(CodegenCompilerJanino.java:115)
        at com.espertech.esper.codegen.compile.CodegenClassGenerator.compile(CodegenClassGenerator.java:40)
        at com.espertech.esper.epl.expression.codegen.ExprNodeCompiler.allocateEvaluator(ExprNodeCompiler.java:91)
        at com.espertech.esper.epl.core.resultset.rowforall.ResultSetProcessorRowForAllForge.getResultSetProcessorFactory(ResultSetProcessorRowForAllForge.java:78)
        at com.espertech.esper.epl.core.resultset.codegen.ResultSetProcessorFactoryCompiler.handleThrowable(ResultSetProcessorFactoryCompiler.java:375)
        at com.espertech.esper.epl.core.resultset.codegen.ResultSetProcessorFactoryCompiler.allocate(ResultSetProcessorFactoryCompiler.java:142)
        at com.espertech.esper.epl.core.resultset.core.ResultSetProcessorFactoryFactory.getProcessorPrototype(ResultSetProcessorFactoryFactory.java:420)
        at com.espertech.esper.core.start.EPStatementStartMethodSelectUtil.prepare(EPStatementStartMethodSelectUtil.java:313)
        at com.espertech.esper.core.start.EPStatementStartMethodSelect.startInternal(EPStatementStartMethodSelect.java:62)
        at com.espertech.esper.core.start.EPStatementStartMethodBase.start(EPStatementStartMethodBase.java:58)
        at com.espertech.esper.core.service.StatementLifecycleSvcImpl.startInternal(StatementLifecycleSvcImpl.java:686)
        at com.espertech.esper.core.service.StatementLifecycleSvcImpl.start(StatementLifecycleSvcImpl.java:649)
        at com.espertech.esper.core.service.StatementLifecycleSvcImpl.createAndStart(StatementLifecycleSvcImpl.java:151)
        at com.espertech.esper.core.service.EPAdministratorImpl.createEPLStmt(EPAdministratorImpl.java:103)
        at com.espertech.esper.core.service.EPAdministratorImpl.createEPL(EPAdministratorImpl.java:61)
        at com.hatchbaby.web.dupes.DuplicateDetectionInterceptor.init(DuplicateDetectionInterceptor.java:71)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at com.hatchbaby.Application.main(Application.java:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NoSuchMethodError: org.codehaus.commons.compiler.Location.<init>(Ljava/lang/String;SS)V
        at org.codehaus.janino.Scanner.location(Scanner.java:261)
        at org.codehaus.janino.Parser.location(Parser.java:2742)
        at org.codehaus.janino.Parser.parseCompilationUnit(Parser.java:155)
        at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:201)
        at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:192)
        at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:50)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.espertech.esper.codegen.compile.CodegenCompilerJanino.compileClass(CodegenCompilerJanino.java:113)
        ... 46 common frames omitted

```

Janino 2.8.7 is using commons-compiler 2.7.8, but the esper jar itself is brining in 3.0.7.  When I force the version in my POM to be commons-compiler 2.7.8, the errors disappear.

**Comment by bernhardttom** [comment]
Esper requires 
<janino.version>3.0.7</janino.version>
why use an old version?
