### ISSUE TITLE
"Too many arguments in method signature" byte code generation error in 7.1.0

### ISSUE THREAD

**Issue by dkcsrd10** [espertechinc/esper#118]
[ResultSetProcessorFactoryCompiler] Failed to code-generate for statement 'Some Statement' result-set-processor requestor-class 'ResultSetProcessorFactoryFactory': Too many arguments in method signature in class file com/espertech/esper/generated/uri_SREsperEngine7/ResultSetProcessorFactoryProvider_c6262fbbe203842acb52a4eaaa1635510
java.lang.ClassFormatError: Too many arguments in method signature in class file com/espertech/esper/generated/uri_SREsperEngine7/ResultSetProcessorFactoryProvider_c6262fbbe203842acb52a4eaaa1635510
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
at org.codehaus.janino.ByteArrayClassLoader.findClass(ByteArrayClassLoader.java:74)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at com.espertech.esper.codegen.compile.CodegenCompilerJanino.compileClass(CodegenCompilerJanino.java:129)
at com.espertech.esper.codegen.compile.CodegenClassGenerator.compile(CodegenClassGenerator.java:40)
at com.espertech.esper.epl.core.resultset.codegen.ResultSetProcessorFactoryCompiler.allocate(ResultSetProcessorFactoryCompiler.java:131)
at com.espertech.esper.epl.core.resultset.core.ResultSetProcessorFactoryFactory.getProcessorPrototype(ResultSetProcessorFactoryFactory.java:393)
at com.espertech.esper.core.start.EPStatementStartMethodSelectUtil.prepare(EPStatementStartMethodSelectUtil.java:312)
at com.espertech.esper.core.start.EPStatementStartMethodSelect.startInternal(EPStatementStartMethodSelect.java:62)
at com.espertech.esper.core.start.EPStatementStartMethodBase.start(EPStatementStartMethodBase.java:58)
at com.espertech.esper.core.service.StatementLifecycleSvcImpl.startInternal(StatementLifecycleSvcImpl.java:691)
at com.espertech.esper.core.service.StatementLifecycleSvcImpl.start(StatementLifecycleSvcImpl.java:654)
at com.espertech.esper.core.service.StatementLifecycleSvcImpl.createAndStart(StatementLifecycleSvcImpl.java:156)
at com.espertech.esper.core.service.EPAdministratorImpl.create(EPAdministratorImpl.java:139)

**Comment by bernhardttom** [comment]
Post the complete test code please or at least the EPL and event types.

**Comment by bernhardttom** [comment]
No code provided, no information to reproduce, closing
