### ISSUE TITLE
Unexpected token exception with enum item starting with the underscore character

### ISSUE THREAD

**Issue by gavol** [espertechinc/esper#131]
Hello,

I am moving to Esper 8 and I am facing an issue that was not there in version 7.1. Actually, the compilation of a statement fails because an enum item starting with '_' is not accepted. If I rename the item removing the underscore, then the statement is properly compiled. I have also tried to use back-ticks, but it does not help.

Here is the stack-trace (the enum is FSM, the problematic item is _EMPTY):

```
com.espertech.esper.compiler.client.EPCompileException: Failed to parse property 'FSM._EMPTY': Unexpected token '_EMPTY' 
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:117)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compile(CompilerHelperModuleProvider.java:74)
	at com.espertech.esper.compiler.internal.util.EPCompilerImpl.compile(EPCompilerImpl.java:169)
Caused by: com.espertech.esper.compiler.client.EPCompileExceptionItem: Failed to parse property 'FSM._EMPTY': Unexpected token '_EMPTY'
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:104)
	... 35 more
Caused by: com.espertech.esper.common.internal.compile.stage2.StatementSpecCompileException: Failed to parse property 'FSM._EMPTY': Unexpected token '_EMPTY'
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:265)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:99)
	... 35 more
Caused by: com.espertech.esper.common.client.PropertyAccessException: Failed to parse property 'FSM._EMPTY': Unexpected token '_EMPTY'
	at com.espertech.esper.common.internal.event.propertyparser.PropertyParserNoDep.parseAndWalkLaxToSimple(PropertyParserNoDep.java:47)
	at com.espertech.esper.common.internal.event.property.PropertyParser.parseAndWalkLaxToSimple(PropertyParser.java:19)
	at com.espertech.esper.common.internal.event.bean.core.BeanEventType.getPropertyType(BeanEventType.java:95)
	at com.espertech.esper.common.internal.event.bean.core.BeanEventType.isProperty(BeanEventType.java:104)
	at com.espertech.esper.common.internal.epl.streamtype.StreamTypeServiceImpl.findByPropertyName(StreamTypeServiceImpl.java:248)
	at com.espertech.esper.common.internal.epl.streamtype.StreamTypeServiceImpl.resolveByPropertyName(StreamTypeServiceImpl.java:158)
	at com.espertech.esper.common.internal.epl.expression.core.ExprIdentNodeUtil.getTypeFromStream(ExprIdentNodeUtil.java:73)
	at com.espertech.esper.common.internal.epl.expression.core.ExprIdentNodeImpl.validate(ExprIdentNodeImpl.java:186)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:246)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:241)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:241)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:241)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtree(ExprNodeUtilityValidate.java:118)
	at com.espertech.esper.common.internal.statement.helper.EPStatementStartMethodHelperValidate.validateNodes(EPStatementStartMethodHelperValidate.java:104)
	at com.espertech.esper.common.internal.context.aifactory.select.StmtForgeMethodSelectUtil.make(StmtForgeMethodSelectUtil.java:270)
	at com.espertech.esper.common.internal.context.aifactory.select.StmtForgeMethodSelect.make(StmtForgeMethodSelect.java:28)
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:206)
	... 36 more
Caused by: com.espertech.esper.common.internal.event.propertyparser.PropertyParseNodepException: Unexpected token '_EMPTY'
	at com.espertech.esper.common.internal.event.propertyparser.Tokenizer.tokenize(Tokenizer.java:44)
	at com.espertech.esper.common.internal.event.propertyparser.PropertyParserNoDep.parseAndWalkLaxToSimple(PropertyParserNoDep.java:43)
	... 52 more
```

Thanks in advance for your help.

**Comment by bernhardttom** [comment]
Can you please also provide the EPL?

**Comment by gavol** [comment]
The EPL can be as simple as:

```
create schema ApplicationConfig as event.config.ApplicationConfig;
create schema ApplicationInfo as event.dynamic.ApplicationInfo;

on ApplicationConfig as appConf
insert into ApplicationInfo
select appConf.name as name, 
	  FSM._EMPTY as state, 
	  false as internalError, 
	  false as busy.
```

**Comment by bernhardttom** [comment]
ok thx, it needed to be clarified.

**Comment by gavol** [comment]
I have a similar issue when enumerations are inner classes.

The simple EPL is:

```
create schema OnDemandAction as event.issue.auto.OnDemandAction;
select * from OnDemandAction(status = OnDemandAction$STATUS.NEW);
```

STATUS is the enumeration defined in the OnDemandAction class.

The exception I receive is the following one:

```
com.espertech.esper.common.client.PropertyAccessException: Failed to parse property 'OnDemandAction$STATUS.DONE': Unexpected token '$STATUS.DONE'
	at com.espertech.esper.common.internal.event.propertyparser.PropertyParserNoDep.parseAndWalkLaxToSimple(PropertyParserNoDep.java:47)
	at com.espertech.esper.common.internal.event.property.PropertyParser.parseAndWalkLaxToSimple(PropertyParser.java:19)
	at com.espertech.esper.common.internal.event.bean.core.BeanEventType.getPropertyType(BeanEventType.java:95)
	at com.espertech.esper.common.internal.event.bean.core.BeanEventType.isProperty(BeanEventType.java:104)
	at com.espertech.esper.common.internal.epl.streamtype.StreamTypeServiceImpl.findByPropertyName(StreamTypeServiceImpl.java:248)
	at com.espertech.esper.common.internal.epl.streamtype.StreamTypeServiceImpl.resolveByPropertyName(StreamTypeServiceImpl.java:158)
	at com.espertech.esper.common.internal.epl.expression.core.ExprIdentNodeUtil.getTypeFromStream(ExprIdentNodeUtil.java:73)
	at com.espertech.esper.common.internal.epl.expression.core.ExprIdentNodeImpl.validate(ExprIdentNodeImpl.java:186)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:246)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:241)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtree(ExprNodeUtilityValidate.java:118)
	at com.espertech.esper.common.internal.compile.stage2.FilterSpecCompiler.validateAllowSubquery(FilterSpecCompiler.java:127)
	at com.espertech.esper.common.internal.compile.stage2.FilterSpecCompiler.makeFilterSpec(FilterSpecCompiler.java:51)
	at com.espertech.esper.common.internal.compile.stage2.StreamSpecCompiler.compileFilter(StreamSpecCompiler.java:123)
	at com.espertech.esper.common.internal.compile.stage2.StreamSpecCompiler.compile(StreamSpecCompiler.java:75)
	at com.espertech.esper.common.internal.compile.stage2.StatementRawCompiler.compile(StatementRawCompiler.java:145)
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:149)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:99)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compile(CompilerHelperModuleProvider.java:74)
	at com.espertech.esper.compiler.internal.util.EPCompilerImpl.compile(EPCompilerImpl.java:169)
Caused by: com.espertech.esper.common.internal.event.propertyparser.PropertyParseNodepException: Unexpected token '$STATUS.DONE'
	at com.espertech.esper.common.internal.event.propertyparser.Tokenizer.tokenize(Tokenizer.java:44)
	at com.espertech.esper.common.internal.event.propertyparser.PropertyParserNoDep.parseAndWalkLaxToSimple(PropertyParserNoDep.java:43)
```

Thanks.

**Comment by bernhardttom** [comment]
try "OnDemandAction.STATUS.DONE"

**Comment by gavol** [comment]
I have tried but then it complains because it cannot resolve the property:

```
com.espertech.esper.compiler.client.EPCompileException: Failed to validate filter expression 'status=OnDemandAction.STATUS.DONE': Failed to resolve property 'OnDemandAction.STATUS.DONE' to a stream or nested property in a stream
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:117)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compile(CompilerHelperModuleProvider.java:74)
	at com.espertech.esper.compiler.internal.util.EPCompilerImpl.compile(EPCompilerImpl.java:169)
Caused by: com.espertech.esper.compiler.client.EPCompileExceptionItem: Failed to validate filter expression 'status=OnDemandAction.STATUS.DONE': Failed to resolve property 'OnDemandAction.STATUS.DONE' to a stream or nested property in a stream
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:104)
	... 37 more
Caused by: com.espertech.esper.common.internal.compile.stage2.StatementSpecCompileException: Failed to validate filter expression 'status=OnDemandAction.STATUS.DONE': Failed to resolve property 'OnDemandAction.STATUS.DONE' to a stream or nested property in a stream
	at com.espertech.esper.common.internal.compile.stage2.StatementRawCompiler.compile(StatementRawCompiler.java:152)
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:149)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:99)
	... 37 more
Caused by: com.espertech.esper.common.internal.epl.expression.core.ExprValidationException: Failed to validate filter expression 'status=OnDemandAction.STATUS.DONE': Failed to resolve property 'OnDemandAction.STATUS.DONE' to a stream or nested property in a stream
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtree(ExprNodeUtilityValidate.java:137)
	at com.espertech.esper.common.internal.compile.stage2.FilterSpecCompiler.validateAllowSubquery(FilterSpecCompiler.java:127)
	at com.espertech.esper.common.internal.compile.stage2.FilterSpecCompiler.makeFilterSpec(FilterSpecCompiler.java:51)
	at com.espertech.esper.common.internal.compile.stage2.StreamSpecCompiler.compileFilter(StreamSpecCompiler.java:123)
	at com.espertech.esper.common.internal.compile.stage2.StreamSpecCompiler.compile(StreamSpecCompiler.java:75)
	at com.espertech.esper.common.internal.compile.stage2.StatementRawCompiler.compile(StatementRawCompiler.java:145)
	... 39 more
Caused by: com.espertech.esper.common.internal.epl.expression.core.ExprValidationPropertyException: Failed to resolve property 'OnDemandAction.STATUS.DONE' to a stream or nested property in a stream
	at com.espertech.esper.common.internal.epl.expression.core.ExprIdentNodeUtil.getSuggestionExceptionSecondStep(ExprIdentNodeUtil.java:176)
	at com.espertech.esper.common.internal.epl.expression.core.ExprIdentNodeUtil.getTypeFromStream(ExprIdentNodeUtil.java:120)
	at com.espertech.esper.common.internal.epl.expression.core.ExprIdentNodeImpl.validate(ExprIdentNodeImpl.java:186)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:246)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:241)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtree(ExprNodeUtilityValidate.java:118)
```

**Comment by gavol** [comment]
Here is the class:

```
package event.issue.auto;


public class OnDemandAction {

    public static enum STATUS {
        NEW,
        PROBLEM,
        FAILED,
        DONE
    }

    private final STATUS status;
    private final String sender;
    private final String command;
    private final String arguments;

    public OnDemandAction(final STATUS status,
                          final String sender,
                          final String command,
                          final String arguments)
    {
        this.status = status;
        this.sender = sender;
        this.command = command;
        this.arguments = arguments;
    }

    public STATUS getStatus() {
        return this.status;
    }

    public String getSender() {
        return this.sender;
    }

    public String getCommand() {
        return this.command;
    }

    public String getArguments() {
        return this.arguments;
    }
}
```

**Comment by gavol** [comment]
Thanks for looking at that.

Which one of the two issues you cannot reproduce? The issue with the underscore or with the nested class?

I have provided the EPL code, the class and the stack trace. Could you please be more precise on what you need?

Do the imports need a different treatment in version 8? I can understand the import can play a role with the nested class issue, but how could be explained that the same enum class does not work only when its items start with an underscore? In the original submission I have stated that replacing _EMPTY with EMPTY fixes the problem. That cannot be an import problem.

Thanks again.

**Comment by bernhardttom** [comment]
Imports are the same for version 8. Can you please provide code to reproduce?

**Comment by gavol** [comment]
OK, I will try to isolate the issue in a simple stand-alone program so that it is easier to reproduce.

Thanks.

**Comment by gavol** [comment]
I have prepared a test case for the issue with the underscore character. In the zip file you will find:

- Test.java - the main class;
- StatusEvent.java - simple class used as event;
- STATUS.java - enum with two items: _INIT and _DONE.

If I replace _INIT and _DONE with INIT and DONE, then the error goes away.

```
SEVERE: Unexpected error compiling statement
com.espertech.esper.common.client.PropertyAccessException: Failed to parse property 'TEST.STATUS._INIT': Unexpected token '_INIT'
	at com.espertech.esper.common.internal.event.propertyparser.PropertyParserNoDep.parseAndWalkLaxToSimple(PropertyParserNoDep.java:47)
	at com.espertech.esper.common.internal.event.property.PropertyParser.parseAndWalkLaxToSimple(PropertyParser.java:19)
	at com.espertech.esper.common.internal.event.bean.core.BeanEventType.getPropertyType(BeanEventType.java:95)
	at com.espertech.esper.common.internal.event.bean.core.BeanEventType.isProperty(BeanEventType.java:104)
	at com.espertech.esper.common.internal.epl.streamtype.StreamTypeServiceImpl.findByPropertyName(StreamTypeServiceImpl.java:248)
	at com.espertech.esper.common.internal.epl.streamtype.StreamTypeServiceImpl.resolveByPropertyName(StreamTypeServiceImpl.java:158)
	at com.espertech.esper.common.internal.epl.expression.core.ExprIdentNodeUtil.getTypeFromStream(ExprIdentNodeUtil.java:73)
	at com.espertech.esper.common.internal.epl.expression.core.ExprIdentNodeImpl.validate(ExprIdentNodeImpl.java:186)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:246)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:241)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtree(ExprNodeUtilityValidate.java:118)
	at com.espertech.esper.common.internal.compile.stage2.FilterSpecCompiler.validateAllowSubquery(FilterSpecCompiler.java:127)
	at com.espertech.esper.common.internal.compile.stage2.FilterSpecCompiler.makeFilterSpec(FilterSpecCompiler.java:51)
	at com.espertech.esper.common.internal.compile.stage2.StreamSpecCompiler.compileFilter(StreamSpecCompiler.java:123)
	at com.espertech.esper.common.internal.compile.stage2.StreamSpecCompiler.compile(StreamSpecCompiler.java:75)
	at com.espertech.esper.common.internal.compile.stage2.StatementRawCompiler.compile(StatementRawCompiler.java:145)
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:149)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:99)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compile(CompilerHelperModuleProvider.java:74)
	at com.espertech.esper.compiler.internal.util.EPCompilerImpl.compile(EPCompilerImpl.java:169)
	at TEST.Test.main(Test.java:54)
```
I will try to do the same for the issue with the inner class.

Thanks and, please, let me know if you have any issue with the attached code.

[underscore.zip](https://github.com/espertechinc/esper/files/2831719/underscore.zip)

**Comment by gavol** [comment]
And here is basically the same example but the STATUS enum is now an inner class of StatusEvent (and I have removed any underscore).

```
SEVERE: Unexpected error compiling statement
com.espertech.esper.common.client.PropertyAccessException: Failed to parse property 'TEST.StatusEvent$STATUS.INIT': Unexpected token '$STATUS.INIT'
	at com.espertech.esper.common.internal.event.propertyparser.PropertyParserNoDep.parseAndWalkLaxToSimple(PropertyParserNoDep.java:47)
	at com.espertech.esper.common.internal.event.property.PropertyParser.parseAndWalkLaxToSimple(PropertyParser.java:19)
	at com.espertech.esper.common.internal.event.bean.core.BeanEventType.getPropertyType(BeanEventType.java:95)
	at com.espertech.esper.common.internal.event.bean.core.BeanEventType.isProperty(BeanEventType.java:104)
	at com.espertech.esper.common.internal.epl.streamtype.StreamTypeServiceImpl.findByPropertyName(StreamTypeServiceImpl.java:248)
	at com.espertech.esper.common.internal.epl.streamtype.StreamTypeServiceImpl.resolveByPropertyName(StreamTypeServiceImpl.java:158)
	at com.espertech.esper.common.internal.epl.expression.core.ExprIdentNodeUtil.getTypeFromStream(ExprIdentNodeUtil.java:73)
	at com.espertech.esper.common.internal.epl.expression.core.ExprIdentNodeImpl.validate(ExprIdentNodeImpl.java:186)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:246)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:241)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtree(ExprNodeUtilityValidate.java:118)
	at com.espertech.esper.common.internal.compile.stage2.FilterSpecCompiler.validateAllowSubquery(FilterSpecCompiler.java:127)
	at com.espertech.esper.common.internal.compile.stage2.FilterSpecCompiler.makeFilterSpec(FilterSpecCompiler.java:51)
	at com.espertech.esper.common.internal.compile.stage2.StreamSpecCompiler.compileFilter(StreamSpecCompiler.java:123)
	at com.espertech.esper.common.internal.compile.stage2.StreamSpecCompiler.compile(StreamSpecCompiler.java:75)
	at com.espertech.esper.common.internal.compile.stage2.StatementRawCompiler.compile(StatementRawCompiler.java:145)
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:149)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:99)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compile(CompilerHelperModuleProvider.java:74)
	at com.espertech.esper.compiler.internal.util.EPCompilerImpl.compile(EPCompilerImpl.java:169)
	at TEST.Test.main(Test.java:53)
```

[inner.zip](https://github.com/espertechinc/esper/files/2831800/inner.zip)

**Comment by bernhardttom** [comment]
The "$" is platform-specific and not supported in EPL. Use "." instead or import "TEST.StatusEvent".

**Comment by gavol** [comment]
It seems to work replacing

TEST.StatusEvent.STATUS.INIT

with 

STATUS.INIT

after importing TEST.StatusEvent.

I have not tried that option because it does not seem a viable solution. Indeed, it may led to clashes. What about having two inner enums with the same name but "belonging" to different external classes?

**Comment by bernhardttom** [comment]
The "$" is part of identifiers so actually it is supported yes.
The code you provided worked for me.

**Comment by gavol** [comment]
Thanks.

Do you have any idea of what I should look at in order to have it working? You have seen the stack trace, I am not inventing it ;-)

If it works for you, then it cannot be a matter of code. Could it be something in the environment?

Is also the underscore example working for you?

**Comment by gavol** [comment]
No way. I am compiling and running in a clean environment, and still it does not work.
Let me say that I have a Linux environment (CentOS 7) and I have tried with Java 8 and also Java 11. The result is always the same.

For completeness, here is the script I use to compile the code:

```
CLASSPATH="/tmp/esper/esper-8.0.0/*:\
/tmp/esper/esper-8.0.0/dependencies/compiler/*"

javac -cp "$CLASSPATH" TEST/*.java
```

and this is the script to run the example:

```
CLASSPATH="/tmp/esper/esper-8.0.0/*:\
/tmp/esper/esper-8.0.0/dependencies/compiler/*:\
/tmp/esper/esper-8.0.0/dependencies/runtime/*:\
."

java -cp "$CLASSPATH" TEST.Test
``` 

The jars have been downloaded directly from the EsperTech web site. /tmp is the base directory where I have extracted the tar archive.

Could you please re-open this issue? I think I have given enough proofs that the issue is real and may be platform related (I think I am not the only one using Esper in Linux). Maybe somebody else could contribute trying to run the example on his/her platform.

**Comment by gavol** [comment]
I have just tried to run the same code in Windows (Java 8, last patch version, 64 bit). Problems are still there with identical stack trace.

**Comment by bernhardttom** [comment]
Both "underscore" and "inner" work for me. Maybe doublecheck your classpath.

**Comment by gavol** [comment]
The classpath I use for compiling and executing the examples is reported a few comments back. In the classpath I have only jars coming with the Esper 8.0.0 distribution.

Could you please share the script/environment you use to compile and run my two examples? At least in this way we can reduce even further the possible domain of errors.

**Comment by gavol** [comment]
Here the explicit classpath I use for compilation and execution.

Compilation:
```
ESPER_BASE_DIR="/tmp/esper/esper-8.0.0/"

CLASSPATH="\
${ESPER_BASE_DIR}/esper-common-8.0.0.jar:\
${ESPER_BASE_DIR}/esper-compiler-8.0.0.jar:\
${ESPER_BASE_DIR}/esper-runtime-8.0.0.jar:\
"

javac -cp "$CLASSPATH" TEST/*.java
```

Execution:
```
ESPER_BASE_DIR="/tmp/esper/esper-8.0.0/"

CLASSPATH="\
${ESPER_BASE_DIR}/esper-common-8.0.0.jar:\
${ESPER_BASE_DIR}/esper-runtime-8.0.0.jar:\
${ESPER_BASE_DIR}/esper-compiler-8.0.0.jar:\
${ESPER_BASE_DIR}/dependencies/runtime/slf4j-api-1.7.25.jar:\
${ESPER_BASE_DIR}/dependencies/compiler/antlr4-runtime-4.7.1.jar:\
${ESPER_BASE_DIR}/dependencies/compiler/janino-3.0.10.jar:\
${ESPER_BASE_DIR}/dependencies/compiler/commons-compiler-3.0.10.jar:\
.\
"

java -cp "$CLASSPATH" TEST.Test
```

**Comment by bernhardttom** [comment]
its because i'm testing against latest and not released. This bug is addressed by the current build.
