### ISSUE TITLE
Shutdown then exception throw

### ISSUE THREAD

**Issue by XiaTianliang** [espertechinc/esper#133]
When shutdown program, after EPServiceProvider destoryed() is called, sometimes exception is thrown as below. From the source code, when destoryed() is called, EPServiceContext will set all service to null(include NamedWindowDispatchService),  the timerTask is not canceled, then null pointer exception will be thrown when access NamedWindowDispatchService.

 [com.espertech.esper.Timer-app_metric_agg-app_metric_agg-0-0] ERROR c.espertech.esper.timer.EPLTimerTask[59] - Timer thread caught unhandled exception: null
java.lang.NullPointerException: null
	at com.espertech.esper.core.service.EPRuntimeImpl.processThreadWorkQueue(EPRuntimeImpl.java:757)
	at com.espertech.esper.core.service.EPRuntimeImpl.processTimeEvent(EPRuntimeImpl.java:547)
	at com.espertech.esper.core.service.EPRuntimeImpl.processEvent(EPRuntimeImpl.java:436)
	at com.espertech.esper.core.service.EPRuntimeImpl.sendEvent(EPRuntimeImpl.java:228)
	at com.espertech.esper.core.service.EPRuntimeImpl.timerCallback(EPRuntimeImpl.java:191)
	at com.espertech.esper.timer.EPLTimerTask.run(EPLTimerTask.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by bernhardttom** [comment]
Please test against 8.0.0
