### ISSUE TITLE
Esper 8 addEventTypeAutoName

### ISSUE THREAD

**Issue by rkimsb2** [espertechinc/esper#135]
I just follow the Getting-Started of reference and just change one thing that calling addEventTypeAutoName method instead of addEventType.

after that, it seems the types are not registered automatically and i gotta error below.
```
Exception in thread "main" java.lang.RuntimeException: com.espertech.esper.compiler.client.EPCompileException: Failed to resolve event type, named window or table by name 'PersonEvent' [@name('my-statement') select name, age from PersonEvent]
	at com.mycompany.myapp.MyApp.main(MyApp.java:33)
Caused by: com.espertech.esper.compiler.client.EPCompileException: Failed to resolve event type, named window or table by name 'PersonEvent' [@name('my-statement') select name, age from PersonEvent]
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:117)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compile(CompilerHelperModuleProvider.java:74)
	at com.espertech.esper.compiler.internal.util.EPCompilerImpl.compile(EPCompilerImpl.java:85)
	at com.mycompany.myapp.MyApp.main(MyApp.java:30)
Caused by: com.espertech.esper.compiler.client.EPCompileExceptionItem: Failed to resolve event type, named window or table by name 'PersonEvent'
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:104)
	... 3 more
Caused by: com.espertech.esper.common.internal.compile.stage2.StatementSpecCompileException: Failed to resolve event type, named window or table by name 'PersonEvent'
	at com.espertech.esper.common.internal.compile.stage2.StatementRawCompiler.compile(StatementRawCompiler.java:152)
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:149)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:99)
	... 3 more
Caused by: com.espertech.esper.common.internal.epl.expression.core.ExprValidationException: Failed to resolve event type, named window or table by name 'PersonEvent'
	at com.espertech.esper.common.internal.compile.stage2.StreamSpecCompiler.resolveTypeName(StreamSpecCompiler.java:641)
	at com.espertech.esper.common.internal.compile.stage2.StreamSpecCompiler.compileFilter(StreamSpecCompiler.java:117)
	at com.espertech.esper.common.internal.compile.stage2.StreamSpecCompiler.compile(StreamSpecCompiler.java:75)
	at com.espertech.esper.common.internal.compile.stage2.StatementRawCompiler.compile(StatementRawCompiler.java:145)
	... 5 more
```

this is my code.

```
package com.mycompany.myapp;

import com.espertech.esper.common.client.EPCompiled;
import com.espertech.esper.common.client.configuration.Configuration;
import com.espertech.esper.compiler.client.CompilerArguments;
import com.espertech.esper.compiler.client.EPCompileException;
import com.espertech.esper.compiler.client.EPCompiler;
import com.espertech.esper.compiler.client.EPCompilerProvider;
import com.espertech.esper.runtime.client.EPDeployException;
import com.espertech.esper.runtime.client.EPDeployment;
import com.espertech.esper.runtime.client.EPRuntime;
import com.espertech.esper.runtime.client.EPRuntimeProvider;
import com.espertech.esper.runtime.client.EPStatement;
import com.mycompany.myapp.event.PersonEvent;

public class MyApp {

	private static String testEPL = "@name('my-statement') select name, age from PersonEvent";

	public static void main(String[] args) {
		Configuration configuration = new Configuration();
//		configuration.getCommon().addEventType(PersonEvent.class);
//		configuration.getCommon().addEventTypeAutoName("com.mycompany.myapp.event");
                configuration.getCommon().addEventTypeAutoName(PersonEvent.class.getPackage().getName());
		
		CompilerArguments cargs = new CompilerArguments(configuration);
		EPCompiler compiler = EPCompilerProvider.getCompiler();

		EPCompiled epCompiled;
		try {
			epCompiled = compiler.compile(testEPL, cargs);
		} catch (EPCompileException ex) {
			// handle exception here
			throw new RuntimeException(ex);
		}

		EPRuntime runtime = EPRuntimeProvider.getDefaultRuntime(configuration);

		EPDeployment deployment;
		try {
			deployment = runtime.getDeploymentService().deploy(epCompiled);
		} catch (EPDeployException ex) {
			// handle exception here
			throw new RuntimeException(ex);
		}

		EPStatement statement = runtime.getDeploymentService().getStatement(deployment.getDeploymentId(),
				"my-statement");

		statement.addListener((newData, oldData, s, r) -> {
			String name = (String) newData[0].get("name");
			int age = (int) newData[0].get("age");
			System.out.println(String.format("Name: %s, Age: %d", name, age));
		});

		
		runtime.getEventService().sendEventBean(new PersonEvent("Peter", 10),
				PersonEvent.class.getSimpleName());
		
	}

}
```

should i call some scanning trigger method?

**Comment by bernhardttom** [comment]
The from-clause  does not allocate types, "create schema" does.
See changes in Esper 8 such as http://www.espertech.com/2018/10/23/esper-8-conceptual-differences-to-older-versions/

**Comment by rkimsb2** [comment]
>The from-clause does not allocate types

Sorry, I don't understand this sentence.
I think this issue is related with **Event Type Import Package**.

I'm curious how addEventType and addEventTypeAutoName works different.
The method addEventType seems to register the schema and addEventTypeAutoName does not.
Does this mean I need to create a schema for every class when I use the addEventTypeAutoName method?

**Comment by bernhardttom** [comment]
Esper 8 does not automatically allocate an event type by putting something in the from-clause.
The "addEventTypeAutoName" works in respect to "create schema".

**Comment by rkimsb2** [comment]
Which means addEventTypeAutoName used for different purpose. Right?

OK. I'll close the issue.
