### ISSUE TITLE
Compile Failed with dot escape

### ISSUE THREAD

**Issue by XiaTianliang** [espertechinc/esper#136]
use java object as event
```java
package esper;
public class NewEvent {
    private String name;
    private Map<String, String> tags;
    // setter and getter
}
```
epl
```sql
module dot_conflict;

import esper.NewEvent;

create schema event as NewEvent;

insert into stream1
select name, tags from event;

select name, tags('a\.b') from stream1.std:groupwin(name, tags('a\.b')).win:length(10)
having count(1) >= 5;

// the flowing statement also not work 
// select name, tags from stream1.std:groupwin(name, tags('a\.b')).win:length(10)
having count(1) >= 5;

```
when deploy the epl file exception comes out

```
[main] INFO com.espertech.esper.core.service.EPServiceProviderImpl - Initializing engine URI 'engine' version 7.1.0
[main] INFO com.espertech.esper.queryplan - Query plans for statement 'stmt_1' expression 'create schema event as NewEvent'
[main] INFO com.espertech.esper.queryplan - Query plans for statement 'stmt_2' expression 'insert into stream1
select name, tags from event'
[main] INFO com.espertech.esper.queryplan - Query plans for statement 'stmt_3' expression 'select name, tags('a\.b') from stream1.std:groupwin(name, tags('a\.b')).win:length(10)
having count(1) >= 5'

com.espertech.esper.client.deploy.DeploymentActionException: Deployment failed in module 'dog_conflict' in module url '/Users/tianliangxia/IdeaProjects/myproject/target/test-classes/dir/dot_conflict.epl' in expression 'select name, tags('a\.b') from stream1.std:groupwi...(107 chars)' : Unexpected exception starting statement: Property name occurs in both the underlying event and in the additional properties [select name, tags('a\.b') from stream1.std:groupwin(name, tags('a\.b')).win:length(10)
having count(1) >= 5]

	at com.espertech.esper.core.deploy.EPDeploymentAdminImpl.buildException(EPDeploymentAdminImpl.java:250)
	at com.espertech.esper.core.deploy.EPDeploymentAdminImpl.deployInternalLockTaken(EPDeploymentAdminImpl.java:213)
	at com.espertech.esper.core.deploy.EPDeploymentAdminImpl.deployInternal(EPDeploymentAdminImpl.java:109)
	at com.espertech.esper.core.deploy.EPDeploymentAdminImpl.deploy(EPDeploymentAdminImpl.java:99)
	at esper.Engine.deployModule(Engine.java:62)
	at esper.EngineTest.testDotConflict(EngineTest.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.espertech.esper.client.deploy.DeploymentItemException: Unexpected exception starting statement: Property name occurs in both the underlying event and in the additional properties [select name, tags('a\.b') from stream1.std:groupwin(name, tags('a\.b')).win:length(10)
having count(1) >= 5]
	at com.espertech.esper.core.deploy.EPDeploymentAdminImpl.deployInternalLockTaken(EPDeploymentAdminImpl.java:190)
	... 27 more
Caused by: com.espertech.esper.client.EPStatementException: Unexpected exception starting statement: Property name occurs in both the underlying event and in the additional properties [select name, tags('a\.b') from stream1.std:groupwin(name, tags('a\.b')).win:length(10)
having count(1) >= 5]
	at com.espertech.esper.core.service.StatementLifecycleSvcImpl.startInternal(StatementLifecycleSvcImpl.java:710)
	at com.espertech.esper.core.service.StatementLifecycleSvcImpl.start(StatementLifecycleSvcImpl.java:654)
	at com.espertech.esper.core.service.StatementLifecycleSvcImpl.createAndStart(StatementLifecycleSvcImpl.java:156)
	at com.espertech.esper.core.service.EPAdministratorImpl.createEPLStmt(EPAdministratorImpl.java:105)
	at com.espertech.esper.core.service.EPAdministratorImpl.createEPL(EPAdministratorImpl.java:83)
	at com.espertech.esper.core.deploy.EPDeploymentAdminImpl.deployInternalLockTaken(EPDeploymentAdminImpl.java:177)
	... 27 more
Caused by: com.espertech.esper.client.EPException: Property name occurs in both the underlying event and in the additional properties
	at com.espertech.esper.event.WrapperEventType.checkForRepeatedPropertyNames(WrapperEventType.java:555)
	at com.espertech.esper.event.WrapperEventType.<init>(WrapperEventType.java:85)
	at com.espertech.esper.event.EventAdapterServiceImpl.createAnonymousWrapperType(EventAdapterServiceImpl.java:760)
	at com.espertech.esper.view.std.MergeViewFactory.attach(MergeViewFactory.java:103)
	at com.espertech.esper.view.ViewServiceImpl.createFactories(ViewServiceImpl.java:61)
	at com.espertech.esper.core.start.EPStatementStartMethodSelectUtil.prepare(EPStatementStartMethodSelectUtil.java:164)
	at com.espertech.esper.core.start.EPStatementStartMethodSelect.startInternal(EPStatementStartMethodSelect.java:62)
	at com.espertech.esper.core.start.EPStatementStartMethodBase.start(EPStatementStartMethodBase.java:58)
	at com.espertech.esper.core.service.StatementLifecycleSvcImpl.startInternal(StatementLifecycleSvcImpl.java:691)
	... 32 more
```

this will only happen if select from a insert stream and access a map property  with dot escape key.

**Comment by bernhardttom** [comment]
test against version 8 please.
A workaround may be to name the output column. "select name, tags('a\.b') as tagab from ..."
