### ISSUE TITLE
create + insert into + select from table error: Failed to resolve event type, named window or table by name 'MyTable' [select * from MyTable]

### ISSUE THREAD

**Issue by Qtianv587** [espertechinc/esper#144]
I was trying to create a table and insert into some data from events, and I test it with the `select`  clause. 
```

esper common version: 8.0.0，
esper runtime version: 8.0.0
esper compiler version: 8.0.0
```

The main code was as following:
```
  def createTable(): Unit = {
    val configuration = new Configuration()

    configuration.getCommon.addEventType(classOf[CreateEvent])
    configuration.getCommon.addEventType(classOf[IDEvent])

    val compileArgs = new CompilerArguments(configuration)

    val sql = "create table MyTable (id string primary key, name string, myMax int);\n" +
      "@name('CreateTableSubscriber') on CreateEvent insert into MyTable select id, name, myMax;\n"
//      "@name('id-event') select MyTable[startKey].name from IDEvent"
//    val insert = "@name('CreateTableSubscriber') insert into MyTable select id, name from CreateEvent\n"
    val select = "@name('id-event') select MyTable[startKey].name from IDEvent"

    val compiler = EPCompilerProvider.getCompiler
    val runtime = EPRuntimeProvider.getDefaultRuntime(configuration)
    val depolyService = runtime.getDeploymentService
    compileArgs.getPath.add(runtime.getRuntimePath)
    val eventSubscriber = new CreateTableSubscriber

    //create table
    println("====create table=====")

    val ePCompiled = compiler.compile(sql, compileArgs)
    val depolyment = depolyService.deploy(ePCompiled)
    val statement = depolyService.getStatement(depolyment.getDeploymentId, eventSubscriber.getName)
    statement.addListener(eventSubscriber)

    val createEvent1 = new CreateEvent(id = "1", name = "ship1", myMax = 1)
    runtime.getEventService.sendEventBean(createEvent1, createEvent1.getClass.getSimpleName)
    val createEvent2 = new CreateEvent(id = "2", name = "ship2", myMax = 2)
    runtime.getEventService.sendEventBean(createEvent2, createEvent2.getClass.getSimpleName)
    val createEvent3 = new CreateEvent(id = "3", name = "ship3", myMax = 3)
    runtime.getEventService.sendEventBean(createEvent3, createEvent3.getClass.getSimpleName)
    val createEvent4 = new CreateEvent(id = "4", name = "ship4", myMax = 4)
    runtime.getEventService.sendEventBean(createEvent4, createEvent4.getClass.getSimpleName)


    val iDEvent1 = new IDEvent(startKey = "1", endKey = "4")
    runtime.getEventService.sendEventBean(iDEvent1, iDEvent1.getClass.getSimpleName)

    TimeUnit.MILLISECONDS.sleep(3000)

//    query table
    val compileArgs2 = new CompilerArguments()
    compileArgs2.getPath.add(runtime.getRuntimePath)
    val ePCompiled2 = compiler.compile(select, compileArgs)
    val depolyment2 = runtime.getDeploymentService.deploy(ePCompiled2)
    val statement2 = runtime.getDeploymentService.getStatement(depolyment2.getDeploymentId, "id-event")
    val iter = statement2.safeIterator()
  }
```

The event called CreateEvent has only three field: id, name, myMax.
The event called IDEvent has only tow field: startKey and endKey.
I don't know why it didn't work and the error info was as following:
```
Exception in thread "main" com.espertech.esper.compiler.client.EPCompileException: Failed to validate select-clause expression 'MyTable[startKey].name': Failed to resolve table name 'MyTable' to a table [@name('id-event') select MyTable[startKey].name from IDEvent]
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:117)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compile(CompilerHelperModuleProvider.java:74)
	at com.espertech.esper.compiler.internal.util.EPCompilerImpl.compile(EPCompilerImpl.java:85)
	at com.blm.gogo.demo.TestDBdemo$.createTable(TestDBdemo.scala:128)
	at com.blm.gogo.demo.TestDBdemo$.main(TestDBdemo.scala:71)
	at com.blm.gogo.demo.TestDBdemo.main(TestDBdemo.scala)
Caused by: com.espertech.esper.compiler.client.EPCompileExceptionItem: Failed to validate select-clause expression 'MyTable[startKey].name': Failed to resolve table name 'MyTable' to a table
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:104)
	... 5 more
Caused by: com.espertech.esper.common.internal.compile.stage2.StatementSpecCompileException: Failed to validate select-clause expression 'MyTable[startKey].name': Failed to resolve table name 'MyTable' to a table
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:260)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:99)
	... 5 more
Caused by: com.espertech.esper.common.internal.epl.expression.core.ExprValidationException: Failed to validate select-clause expression 'MyTable[startKey].name': Failed to resolve table name 'MyTable' to a table
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtree(ExprNodeUtilityValidate.java:137)
	at com.espertech.esper.common.internal.epl.resultset.core.ResultSetProcessorFactoryFactory.validateSelectAssignColNames(ResultSetProcessorFactoryFactory.java:805)
	at com.espertech.esper.common.internal.epl.resultset.core.ResultSetProcessorFactoryFactory.getProcessorPrototype(ResultSetProcessorFactoryFactory.java:151)
	at com.espertech.esper.common.internal.context.aifactory.select.StmtForgeMethodSelectUtil.make(StmtForgeMethodSelectUtil.java:274)
	at com.espertech.esper.common.internal.context.aifactory.select.StmtForgeMethodSelect.make(StmtForgeMethodSelect.java:28)
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:206)
	... 6 more
Caused by: com.espertech.esper.common.internal.epl.expression.core.ExprValidationException: Failed to resolve table name 'MyTable' to a table
	at com.espertech.esper.common.internal.epl.expression.table.ExprTableAccessNode.validate(ExprTableAccessNode.java:68)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:246)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtree(ExprNodeUtilityValidate.java:118)
	... 11 more
```
Thanks for any reply.

**Comment by Qtianv587** [comment]
@bernhardttom @bernhardttom2 @yangguang760 @raguessner @markcshelton

**Comment by bernhardttom** [comment]
The compiler has the concept of a path and only sees the EPL objects (such as tables) that are on the path. You can add all existing objects to the path and the doc for that is "15.6.2.1. Compiling Against a Runtime" step "arguments.getPath().add(runtime.getRuntimePath());"

**Comment by Qtianv587** [comment]
Thanks a lot! It works!
