### ISSUE TITLE
Failed to deploy: Failed to obtain connection cache: Cannot locate configuration information for database 'xxxx'

### ISSUE THREAD

**Issue by Qtianv587** [espertechinc/esper#146]
I want to use sql in EPL to access data from mysql database. It worked in my own PC but didn't work  in remote server.
The main code is as following:
```
EPDeployment deployment;
        EPStatement statement;
        if (!runtime.getDeploymentService().isDeployed(DEPLOYMENT_ID)) {//
            String eplFile = "optiontrade.epl";
            try {
                Module module = EPCompilerProvider.getCompiler().readModule(eplFile, this.getClass().getClassLoader());

                Configuration configuration = runtime.getConfigurationDeepCopy();

                ConfigurationCommonDBRef dbConfig = this.getDBConfig();

                configuration.getCommon().addDatabaseReference("gogo", dbConfig);

                CompilerArguments args = new CompilerArguments(configuration);

                args.getPath().add(runtime.getRuntimePath());

                EPCompiled compiled = EPCompilerProvider.getCompiler().compile(module, args);

                EPDeploymentService epDeploymentService = runtime.getDeploymentService();

                deployment = epDeploymentService.deploy(compiled, new DeploymentOptions().setDeploymentId(DEPLOYMENT_ID));

//                TriggerInsert triggerInsert = new TriggerInsert(1);
//
//                runtime.getEventService().sendEventBean(triggerInsert, triggerInsert.getClass().getSimpleName());

                EPStatement statement1 = epDeploymentService.getStatement(DEPLOYMENT_ID, "TerminalTable");

                Iterator iter = statement1.iterator();

                statement = epDeploymentService.getStatement(DEPLOYMENT_ID, "QueryTerminalTable");

            } catch (Exception ex) {
                log.error("Unexpected exception compiling deploying '" + eplFile + "': " + ex.getMessage(), ex);
                return;
            }
        }else {
            statement = runtime.getDeploymentService().getStatement(DEPLOYMENT_ID, "QueryTerminalTable");
        }
        //
        statement.addListener(new QueryTableSubscriber());
```
The getDBConfig() is as following:
```
public ConfigurationCommonDBRef getDBConfig() {
        Properties props = new Properties();
        ConfigurationCommonDBRef dbConfig = new ConfigurationCommonDBRef();
        props.put("username", "xxxxxx");
        props.put("password", "xxxxxx");
        props.put("driverClassName", "com.mysql.jdbc.Driver");
        props.put("url", "jdbc:mysql://xx.xx.xx.xx:3306/gogo");
        props.put("initialSize", "2");
        props.put("validationQuery", "select 1 from dual");
        dbConfig.setDataSourceFactory(props, BasicDataSourceFactory.class.getName());
        dbConfig.setConnectionLifecycleEnum(ConfigurationCommonDBRef.ConnectionLifecycleEnum.POOLED);

        return dbConfig;
    }
```

The EPL clause is placed in a module file:
```
@Name('TriggerInsert Event Type')
@public @buseventtype create schema TriggerInsert TriggerInsert;

@Name('TableQuery Event Type')
@public @buseventtype create schema IDEvent IDEvent;

//@name('test-statement')
//@public @buseventtype select mmsi, imo from AisInfo;



@Name("TerminalTable")
create table TerminalTable (
    terminalId string primary key,
    lon double,
    lat double,
    imex string,
    scope string
);

@Name("test")
select * from sql:gogo['select terminal_id as terminalId from TNG11_terminal'];



//@Name("InsertIntoTerminalTable")
//insert into TerminalTable
//select terminalId, lon, lat, imex, scope from TriggerInsert,
//sql:gogo['select terminal_id as terminalId, lon, lat, imex, AsText(outline) as scope from TNG11_terminal'];



//@Name("QueryTerminalTable")
//on IDEvent ie
//select tt.terminalId, tt.lon, tt.lat, tt.imex, tt.scope from TerminalTable tt;

```
The error info is as following:
```
com.espertech.esper.runtime.client.EPDeployException: Failed to deploy: Failed to obtain connection cache: Cannot locate configuration information for database 'gogo'
	at com.espertech.esper.runtime.internal.kernel.service.Deployer.deploySafe(Deployer.java:380)
	at com.espertech.esper.runtime.internal.kernel.service.Deployer.deploy(Deployer.java:107)
	at com.espertech.esper.runtime.internal.kernel.service.Deployer.deployFresh(Deployer.java:95)
	at com.espertech.esper.runtime.internal.kernel.service.EPDeploymentServiceImpl.deploy(EPDeploymentServiceImpl.java:83)
	at com.blm.cep.server.AisContextListener.contextInitialized(AisContextListener.java:103)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:953)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:558)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:918)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:370)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:848)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:167)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:419)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:386)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.espertech.esper.server.webapp.WebAppPlugin.postInitialize(WebAppPlugin.java:96)
	at com.espertech.esper.runtime.internal.kernel.service.EPRuntimeImpl.postInitialize(EPRuntimeImpl.java:126)
	at com.espertech.esper.runtime.client.EPRuntimeProvider.getRuntime(EPRuntimeProvider.java:91)
	at com.espertech.esper.server.Bootstrap.main(Bootstrap.java:310)
Caused by: com.espertech.esper.common.client.EPException: Failed to obtain connection cache: Cannot locate configuration information for database 'gogo'
	at com.espertech.esper.common.internal.epl.historical.database.core.HistoricalEventViewableDatabaseFactory.activate(HistoricalEventViewableDatabaseFactory.java:47)
	at com.espertech.esper.common.internal.context.activator.ViewableActivatorHistorical.activate(ViewableActivatorHistorical.java:30)
	at com.espertech.esper.common.internal.context.aifactory.select.StatementAgentInstanceFactorySelect.newContext(StatementAgentInstanceFactorySelect.java:151)
	at com.espertech.esper.common.internal.context.aifactory.select.StatementAgentInstanceFactorySelect.newContext(StatementAgentInstanceFactorySelect.java:56)
	at com.espertech.esper.runtime.internal.kernel.service.DeployerStatement.startStatementNoContext(DeployerStatement.java:126)
	at com.espertech.esper.runtime.internal.kernel.service.DeployerStatement.deployStatement(DeployerStatement.java:49)
	at com.espertech.esper.runtime.internal.kernel.service.Deployer.deploySafe(Deployer.java:377)
	... 33 more
Caused by: com.espertech.esper.common.internal.epl.historical.database.connection.DatabaseConfigException: Cannot locate configuration information for database 'gogo'
	at com.espertech.esper.common.internal.epl.historical.database.connection.DatabaseConfigServiceImpl.getConnectionCache(DatabaseConfigServiceImpl.java:102)
	at com.espertech.esper.common.internal.epl.historical.database.core.HistoricalEventViewableDatabaseFactory.activate(HistoricalEventViewableDatabaseFactory.java:45)
	... 39 more
```

I tried my best to solve this but failed. I'm begging for your help.
@yangguang760 @ajaxx @bernhardttom @bernhardttom2

**Comment by bernhardttom** [comment]
When getting the runtime with "EPRuntimeProvider.getRuntime(configuration)" make sure that configuration object also has the database.

**Comment by Qtianv587** [comment]
@bernhardttom 
I make some changes, but it still didn't work. The errors is still 
`Failed to deploy: Failed to obtain connection cache: Cannot locate configuration information for database 'gogo'`
```
Configuration configuration = runtime.getConfigurationDeepCopy();

        ConfigurationCommonDBRef dbConfig = this.getDBConfig();

        configuration.getCommon().addDatabaseReference("gogo", dbConfig);

        EPRuntime epRuntime = EPRuntimeProvider.getDefaultRuntime(configuration);

        CompilerArguments args = new CompilerArguments(configuration);

        EPDeployment deployment;
        EPStatement statement;
        if (!epRuntime.getDeploymentService().isDeployed(DEPLOYMENT_ID)) {
            String eplFile = "optiontrade.epl";
            try {
                Module module = EPCompilerProvider.getCompiler().readModule(eplFile, this.getClass().getClassLoader());

                args.getPath().add(epRuntime.getRuntimePath());

                EPCompiled compiled = EPCompilerProvider.getCompiler().compile(module, args);

                EPDeploymentService epDeploymentService = epRuntime.getDeploymentService();

                deployment = epDeploymentService.deploy(compiled, new DeploymentOptions().setDeploymentId(DEPLOYMENT_ID));

//                TriggerInsert triggerInsert = new TriggerInsert(1);
//
//                runtime.getEventService().sendEventBean(triggerInsert, triggerInsert.getClass().getSimpleName());

                EPStatement statement1 = epDeploymentService.getStatement(DEPLOYMENT_ID, "TerminalTable");

                Iterator iter = statement1.iterator();

                statement = epDeploymentService.getStatement(DEPLOYMENT_ID, "QueryTerminalTable");

            } catch (Exception ex) {
                log.error("Unexpected exception compiling deploying '" + eplFile + "': " + ex.getMessage(), ex);
                return;
            }
        }else {
            statement = epRuntime.getDeploymentService().getStatement(DEPLOYMENT_ID, "QueryTerminalTable");
        }

        statement.addListener(new QueryTableSubscriber());
```

**Comment by Qtianv587** [comment]
@bernhardttom 
Maybe I should describe my question once again. I package my project as a `.jar` file and upload it to remote server and execute. 
Just guessing, maybe before the main method executes  the module file called `optiontrade.epl` has been compiled without parameters like url, username etc. Maybe it's the reason.

**Comment by bernhardttom** [comment]
Try to call "EPRuntimeProvider.getDefaultRuntime(configuration);" exactly once. The code you have posted does "runtime.getConfigurationDeepCopy();" and after that it does "EPRuntimeProvider.getDefaultRuntime(configuration);" however the runtime already exists at that time.
