### ISSUE TITLE
method 'countOf', expecting collection of event-type or scalar values as input, received class java.util.Collection

### ISSUE THREAD

**Issue by mikolajmitura** [espertechinc/esper#149]
Hello,
in 8.1.0 version when I tried use below query 
```sql
select cast(value.some_collection?, java.util.Collection).countOf() as cast_collection from Record#time_batch(2 sec)
```
I got stack trace:
```console
Caused by: com.espertech.esper.common.internal.epl.expression.core.ExprValidationException: Invalid input for built-in enumeration method 'countOf', expecting collection of event-type or scalar values as input, received class java.util.Collection
	at com.espertech.esper.common.internal.epl.enummethod.dot.ExprDotForgeEnumMethodBase.init(ExprDotForgeEnumMethodBase.java:86)
	at com.espertech.esper.common.internal.epl.expression.dot.core.ExprDotNodeUtility.getChainEvaluators(ExprDotNodeUtility.java:228)
	at com.espertech.esper.common.internal.epl.expression.dot.core.ExprDotNodeImpl.validate(ExprDotNodeImpl.java:135)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:246)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtree(ExprNodeUtilityValidate.java:118)
	... 10 more
```
this 'some_collection' is dynamic field not always exist in value object (inheritance issue)

when some_collection is always present in given event type then below query works fine (But I cannot operate only on concrete class):  
```sql
select value.someCollection.countOf() as cast_collection from Record#time_batch(2 sec)
```

when I invoked below query
```sql
insert into SomeTable
select 
cast(value.some_collection?, java.util.Collection) as cast_collection, 
value.some_collection? as raw_collection 
from Record#time_batch(2 sec)
```
Then in SomeTable the cast_collection and raw_collection have the same value...
always is the java.util.Collection I suppose so 'countOf()' and other scalar function should works properly on java.util.Collection provided by 'cast' function too.

**Comment by bernhardttom** [comment]
workaround is to use a UDF

**Comment by mikolajmitura** [comment]
Another workaround is to query like below:
```sql
select cast(value.some_collection?, java.util.Collection).toArray().countOf() as cast_collection from Record#time_batch(2 sec)
```
with ".toArray()" any method like "AllOf()" and "AnyOf()" can be invoked but "cast()" function is useful then every nested getter can be invoked. 

example: 
```sql
select 
	cast(cast(value.some_collection?, java.util.Collection).toArray().firstof(), com.some.FirstTypeInList)
                                                               .getSomeList().countOf() as cancellations_size
from Record#time(2 sec) 
```
class com.some.FirstTypeInList have getter method 'getSomeList()'
Here on result of getSomeList() can be invoked method like "AllOf()" and "AnyOf()" (every of scalar, array data)
