### ISSUE TITLE
init value for columns that are aggregation functions

### ISSUE THREAD

**Issue by mikolajmitura** [espertechinc/esper#154]
Is there a some way to populate columns which is aggregation function type with initial values? 
example table: 

```sql
create table Table_Sum (some_id long primary key, sum_ count(*))
```

My purpose is restore (after shutdown) earlier calculations and continue with normal "into table" statement.
I know that it cannot do through epl statement because I got below error. 
I tried query like this: 
```sql 
insert into Table_Sum (some_id, _sum_) values (555, 100)
```

```bash
Caused by: com.espertech.esper.common.internal.epl.expression.core.ExprValidationException: Column 'sum_' could not be assigned to any of the properties of the underlying type (missing column names, event property, setter method or constructor?)
	at com.espertech.esper.common.internal.epl.resultset.select.core.SelectExprInsertEventBeanFactory.initializeSetterManufactor(SelectExprInsertEventBeanFactory.java:277)
	at com.espertech.esper.common.internal.epl.resultset.select.core.SelectExprInsertEventBeanFactory.getInsertUnderlyingNonJoin(SelectExprInsertEventBeanFactory.java:107)
	at com.espertech.esper.common.internal.epl.resultset.select.core.SelectExprProcessorHelper.getForge(SelectExprProcessorHelper.java:830)
	at com.espertech.esper.common.internal.epl.resultset.select.core.SelectExprProcessorFactory.getProcessorInternal(SelectExprProcessorFactory.java:138)
	at com.espertech.esper.common.internal.epl.resultset.select.core.SelectExprProcessorFactory.getProcessor(SelectExprProcessorFactory.java:43)
	at com.espertech.esper.common.internal.epl.fafquery.querymethod.FAFQueryMethodIUDInsertIntoForge.initExec(FAFQueryMethodIUDInsertIntoForge.java:99)
	at com.espertech.esper.common.internal.epl.fafquery.querymethod.FAFQueryMethodIUDBaseForge.<init>(FAFQueryMethodIUDBaseForge.java:113)
	at com.espertech.esper.common.internal.epl.fafquery.querymethod.FAFQueryMethodIUDInsertIntoForge.<init>(FAFQueryMethodIUDInsertIntoForge.java:50)
	at com.espertech.esper.compiler.internal.util.CompilerHelperFAFProvider.compile(CompilerHelperFAFProvider.java:99)
	at com.espertech.esper.compiler.internal.util.EPCompilerImpl.compileQueryInternal(EPCompilerImpl.java:247)
	... 4 more
```

Thanks in advance for response.

**Comment by bernhardttom** [comment]
Aggregation columns are not simple values but are actually made up  of a couple of fields (except count which is just a count). Therefore they cannot be inserted into. The can be changed using "into table".
