### ISSUE TITLE
Failed to compile code System.currentTimeMillis().minus(7 hours)

### ISSUE THREAD

**Issue by ravigit** [espertechinc/esper#167]
The stack trace is as follows:

17:24:01.429  [clojure-agent-send-off-pool-26] WARN  com.espertech.esper.epl.expression.codegen.ExprNodeCompiler - Failed to code-generate for statement 'testsss' expression 'System.currentTimeMillis().minus(7 hours)' requestor-class 'EvalSelectNoWildcardMap' (invalid code follows, falling back to regular evaluation): Failed to compile generated code
code-in-error (please provide with issue reports):
   1  package com.espertech.esper.generated.uri_node453;
   2  import java.lang.reflect.Method;
   3  import java.util.Calendar;
   4  import com.espertech.esper.epl.expression.dot.ExprDotNodeForgeStaticMethodEval;
   5  import com.espertech.esper.epl.datetime.calop.CalendarPlusMinusForgeOp;
   6  import com.espertech.esper.client.util.TimePeriod;
   7  import com.espertech.esper.client.EventBean;
   8  import com.espertech.esper.epl.expression.core.ExprEvaluator;
   9  import sun.util.calendar.ZoneInfo;
  10  import com.espertech.esper.epl.expression.core.ExprEvaluatorContext;
  11  public class ExprEvaluator_cdca27937fe3c44f3a223d215a719440b implements ExprEvaluator {
  12    final ZoneInfo mb1;
  13    final Method mb0;
  14
  15    public ExprEvaluator_cdca27937fe3c44f3a223d215a719440b(ZoneInfo p1,Method p0){
  16      this.mb1=p1;
  17      this.mb0=p0;
  18    }
  19
  20    // ExprNodeCompiler
  21    public Object evaluate(EventBean[] eventsPerStream,boolean isNewData,ExprEvaluatorContext exprEvalCtx){
  22      return m0();
  23    }
  24
  25    // ExprDotNodeForgeStaticMethodEval
  26    long m0(){
  27      try {
  28        long result=System.currentTimeMillis();
  29        long chain=m1(result);
  30        return chain;
  31      } catch (Throwable t) {
  32        Object[] argArray=new Object[0];
  33        ExprDotNodeForgeStaticMethodEval.staticMethodEvalHandleInvocationException("testsss",mb0,"System",argArray,t,false);
  34      }
  35      return null;
  36    }
  37
  38    // ExprDotNodeUtility
  39    long m1(long inner){
  40      long wrapped=inner;
  41      long r0=m2(wrapped);
  42      return r0;
  43    }
  44
  45    // ExprDotDTForge
  46    long m2(long target){
  47      return m3(target);
  48    }
  49
  50    // DTLocalCalOpsLongEval
  51    long m3(long target){
  52      Calendar cal=Calendar.getInstance(mb1);
  53      long remainder=m4(target,cal);
  54      CalendarPlusMinusForgeOp.actionCalendarPlusMinusTimePeriod(cal,-1,m5());
  55      return cal.getTimeInMillis();
  56    }
  57
  58    // TimeAbacusMilliseconds
  59    long m4(long fromTime,Calendar cal){
  60      cal.setTimeInMillis(fromTime);
  61      return 0;
  62    }
  63
  64    // ExprTimePeriodForge
  65    TimePeriod m5(){
  66      Integer year=null;
  67      Integer month=null;
  68      Integer week=null;
  69      Integer day=null;
  70      Integer hours=7;
  71      Integer minutes=null;
  72      Integer seconds=null;
  73      Integer milliseconds=null;
  74      Integer microseconds=null;
  75      return new TimePeriod(year,month,week,day,hours,minutes,seconds,milliseconds,microseconds);
  76    }
  77  }

com.espertech.esper.codegen.compile.CodegenCompilerException: Failed to compile generated code
	at com.espertech.esper.codegen.compile.CodegenCompilerJanino.compileClass(CodegenCompilerJanino.java:115)
	at com.espertech.esper.codegen.compile.CodegenClassGenerator.compile(CodegenClassGenerator.java:40)
	at com.espertech.esper.epl.expression.codegen.ExprNodeCompiler.allocateEvaluator(ExprNodeCompiler.java:91)
	at com.espertech.esper.epl.util.ExprNodeUtilityRich.getEvaluatorsMayCompile(ExprNodeUtilityRich.java:983)
	at com.espertech.esper.epl.core.select.eval.EvalSelectNoWildcardMap.getSelectExprProcessor(EvalSelectNoWildcardMap.java:50)
	at com.espertech.esper.epl.core.select.SelectExprResultProcessor.getSelectExprProcessor(SelectExprResultProcessor.java:58)
	at com.espertech.esper.epl.core.select.SelectExprProcessorCompiler.allocateSelectExprEvaluator(SelectExprProcessorCompiler.java:46)
	at com.espertech.esper.epl.core.resultset.handthru.ResultSetProcessorSimpleForge.getResultSetProcessorFactory(ResultSetProcessorSimpleForge.java:73)
	at com.espertech.esper.epl.core.resultset.codegen.ResultSetProcessorFactoryCompiler.handleThrowable(ResultSetProcessorFactoryCompiler.java:375)
	at com.espertech.esper.epl.core.resultset.codegen.ResultSetProcessorFactoryCompiler.allocate(ResultSetProcessorFactoryCompiler.java:142)
	at com.espertech.esper.epl.core.resultset.core.ResultSetProcessorFactoryFactory.getProcessorPrototype(ResultSetProcessorFactoryFactory.java:402)
	at com.espertech.esper.core.start.EPStatementStartMethodSelectUtil.prepare(EPStatementStartMethodSelectUtil.java:312)
	at com.espertech.esper.core.start.EPStatementStartMethodSelect.startInternal(EPStatementStartMethodSelect.java:62)
	at com.espertech.esper.core.start.EPStatementStartMethodBase.start(EPStatementStartMethodBase.java:58)
	at com.espertech.esper.core.service.StatementLifecycleSvcImpl.startInternal(StatementLifecycleSvcImpl.java:691)
	at com.espertech.esper.core.service.StatementLifecycleSvcImpl.start(StatementLifecycleSvcImpl.java:654)
	at com.espertech.esper.core.service.StatementLifecycleSvcImpl.createAndStart(StatementLifecycleSvcImpl.java:156)
	at com.espertech.esper.core.service.EPAdministratorImpl.createEPLStmt(EPAdministratorImpl.java:105)
	at com.espertech.esper.core.service.EPAdministratorImpl.createEPL(EPAdministratorImpl.java:75)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
         ……….
         ……….
         ……….
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at jett.argus_compute.dtm_events$with_timeout$fn__10051.invoke(dtm_events.clj:186)
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.commons.compiler.CompileException: Line 35, Column 11: Assignment conversion not possible from type "void" to type "long"
	at org.codehaus.janino.UnitCompiler.compileError(UnitCompiler.java:11672)
	at org.codehaus.janino.UnitCompiler.assignmentConversion(UnitCompiler.java:10528)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2606)
	at org.codehaus.janino.UnitCompiler.access$2700(UnitCompiler.java:212)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1460)
	at org.codehaus.janino.UnitCompiler$6.visitReturnStatement(UnitCompiler.java:1443)
	at org.codehaus.janino.Java$ReturnStatement.accept(Java.java:3389)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1443)
	at org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1523)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3052)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1313)
	at org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1286)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:785)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:436)
	at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:212)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:390)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:385)
	at org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1405)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:385)
	at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:357)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:234)
	at org.codehaus.janino.SimpleCompiler.compileToClassLoader(SimpleCompiler.java:446)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:213)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:204)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:50)
	at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.espertech.esper.codegen.compile.CodegenCompilerJanino.compileClass(CodegenCompilerJanino.java:113)
	... 48 common frames omitted

**Comment by ravigit** [comment]
Using esper 7.1.0. jdk 8

**Comment by bernhardttom** [comment]
Test against the current version please.
