### ISSUE TITLE
SingleRowFunction not resolved with single "." string literal parameter

### ISSUE THREAD

**Issue by icholy** [espertechinc/esper#175]
When I have a single-row function with a single string parameter, the compiler always fails when I try to pass a string literal with a dot in it.

``` java
import com.espertech.esper.common.client.configuration.Configuration;
import com.espertech.esper.compiler.client.CompilerArguments;
import com.espertech.esper.compiler.client.EPCompilerProvider;

public class Main {
    public static void main(String[] args) throws Exception {
        var compiler = EPCompilerProvider.getCompiler();
        var configuration = new Configuration();
        configuration.getCompiler().addPlugInSingleRowFunction("Bar", Main.class.getCanonicalName(), "Bar");
        var arguments = new CompilerArguments(configuration);

        // this works fine
        compiler.compile("create variable Object Foo = Bar(\"test\")", arguments);

        // this doesn't work
        compiler.compile("create variable Object Foo = Bar(\".\")", arguments);
    }

    public static String Bar(String input) {
        return input;
    }
}
```

```
com.espertech.esper.compiler.client.EPCompileException: Failed to validate variable-assignment expression 'Bar(".")': Failed to resolve enumeration method, date-time method or mapped property 'Bar(".")': Failed to resolve '.Bar' to a property, single-row function, aggregation function, script, stream or class name [create variable Object Foo = Bar(".")]
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:150)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compile(CompilerHelperModuleProvider.java:82)
	at com.espertech.esper.compiler.internal.util.EPCompilerImpl.compile(EPCompilerImpl.java:89)
	at Main.main(Main.java:19)
Caused by: com.espertech.esper.compiler.client.EPCompileExceptionItem: Failed to validate variable-assignment expression 'Bar(".")': Failed to resolve enumeration method, date-time method or mapped property 'Bar(".")': Failed to resolve '.Bar' to a property, single-row function, aggregation function, script, stream or class name
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:125)
	... 3 more
Caused by: com.espertech.esper.common.internal.compile.stage2.StatementSpecCompileException: Failed to validate variable-assignment expression 'Bar(".")': Failed to resolve enumeration method, date-time method or mapped property 'Bar(".")': Failed to resolve '.Bar' to a property, single-row function, aggregation function, script, stream or class name
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:278)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:110)
	... 3 more
Caused by: com.espertech.esper.common.internal.epl.expression.core.ExprValidationException: Failed to validate variable-assignment expression 'Bar(".")': Failed to resolve enumeration method, date-time method or mapped property 'Bar(".")': Failed to resolve '.Bar' to a property, single-row function, aggregation function, script, stream or class name
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtree(ExprNodeUtilityValidate.java:137)
	at com.espertech.esper.common.internal.context.aifactory.createvariable.StmtForgeMethodCreateVariable.make(StmtForgeMethodCreateVariable.java:77)
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:214)
	... 4 more
Caused by: com.espertech.esper.common.internal.epl.expression.core.ExprValidationException: Failed to resolve enumeration method, date-time method or mapped property 'Bar(".")': Failed to resolve '.Bar' to a property, single-row function, aggregation function, script, stream or class name
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.resolveStaticMethodOrField(ExprNodeUtilityValidate.java:355)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:254)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtree(ExprNodeUtilityValidate.java:118)
	... 6 more

Process finished with exit code 0
```

**Comment by icholy** [comment]
I've traced the problem down to https://github.com/espertechinc/esper/blob/b2b2787cde3c988c057ab57a2f2efaebde6d0bb8/common/src/main/java/com/espertech/esper/common/internal/event/propertyparser/PropertyParserNoDep.java#L58

When there's a `.` in the argument string, then the `MappedPropertyParseResult` will have an empty string as the `className` instead of `null`

``` java
import com.espertech.esper.common.internal.event.property.MappedPropertyParseResult;
import com.espertech.esper.common.internal.event.propertyparser.PropertyParserNoDep;

public class Main {
    public static void main(String[] args) throws Exception {
        System.out.printf("No Dot: %s\n", format(PropertyParserNoDep.parseMappedProperty("Bar(\"test\")")));
        System.out.printf("With Dot: %s\n", format(PropertyParserNoDep.parseMappedProperty("Bar(\".\")")));
    }

    private static String format(MappedPropertyParseResult result) {
        return String.format("ClassName=%s MethodName=%s ArgString=%s", result.getClassName(), result.getMethodName(), result.getArgString());
    }
}
```

Output: 
```
No Dot: ClassName=null MethodName=Bar ArgString=test
With Dot: ClassName= MethodName=Bar ArgString=.
```

This is problem here, because since the `className` isn't `null`, it's assuming it's a static method instead of a single-row function.

https://github.com/espertechinc/esper/blob/master/common/src/main/java/com/espertech/esper/common/internal/epl/expression/core/ExprNodeUtilityValidate.java#L343
