### ISSUE TITLE
Fails to compile "NOT variable.method()"

### ISSUE THREAD

**Issue by icholy** [espertechinc/esper#179]
Here's a minimal example:

```
// setup
create schema S0 as (text string);
create variable string thing = "Hello World";

// these variations all work
create context ctx1 initiated S0(text.contains(text));
create context ctx2 initiated S0(not text.contains(text));
create context ctx3 initiated S0(text.contains(thing));
create context ctx4 initiated S0(not text.contains(thing));
create context ctx5 initiated S0(thing.contains(text));
  
// fails when using: not operator + boolean method on variable 
create context ctx6 initiated S0(not thing.contains(text));
```

StackTrace:
```
Exception in thread "main" com.espertech.esper.compiler.client.EPCompileException: The operation is not available at compile time [create context ctx6   initiated S0(not thing.contains(text))]
Caused by: com.espertech.esper.compiler.client.EPCompileExceptionItem: The operation is not available at compile time
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:125)
	... 5 more
Caused by: com.espertech.esper.common.internal.compile.stage2.StatementSpecCompileException: The operation is not available at compile time
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:283)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:110)
	... 5 more
Caused by: java.lang.UnsupportedOperationException: The operation is not available at compile time
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityMake.makeUnsupportedCompileTime(ExprNodeUtilityMake.java:173)
	at com.espertech.esper.common.internal.epl.expression.dot.core.ExprDotNodeForgeVariable.getExprEvaluator(ExprDotNodeForgeVariable.java:40)
	at com.espertech.esper.common.internal.epl.expression.ops.ExprNotNode.validate(ExprNotNode.java:44)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:246)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtree(ExprNodeUtilityValidate.java:118)
	at com.espertech.esper.common.internal.compile.stage2.FilterSpecCompiler.validateAllowSubquery(FilterSpecCompiler.java:131)
	at com.espertech.esper.common.internal.compile.stage2.FilterSpecCompiler.makeFilterSpec(FilterSpecCompiler.java:52)
	at com.espertech.esper.common.internal.compile.stage2.StreamSpecCompiler.compileFilter(StreamSpecCompiler.java:129)
	at com.espertech.esper.common.internal.compile.stage2.StreamSpecCompiler.compile(StreamSpecCompiler.java:79)
	at com.espertech.esper.common.internal.context.aifactory.createcontext.StmtForgeMethodCreateContext.validateRewriteContextCondition(StmtForgeMethodCreateContext.java:452)
	at com.espertech.esper.common.internal.context.aifactory.createcontext.StmtForgeMethodCreateContext.validateContextDetail(StmtForgeMethodCreateContext.java:297)
	at com.espertech.esper.common.internal.context.aifactory.createcontext.StmtForgeMethodCreateContext.make(StmtForgeMethodCreateContext.java:84)
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:214)
	... 6 more

Process finished with exit code 1
```

**Comment by icholy** [comment]
Looks like `ExprDotNodeForgeVariable` needs to be updated to return an instance of `ExprDotNodeForgeVariableEval`
https://github.com/espertechinc/esper/blob/d8edd5bb463f0c9a4ee549565cffb5da3cd3b2c6/common/src/main/java/com/espertech/esper/common/internal/epl/expression/dot/core/ExprDotNodeForgeVariable.java#L39-L41
