### ISSUE TITLE
On-merge with assign column as typed event causes cast exception when assigned using stream alias for OA and Map types

### ISSUE THREAD

**Issue by icholy** [espertechinc/esper#185]
``` java
import com.espertech.esper.common.client.configuration.Configuration;
import com.espertech.esper.compiler.client.CompilerArguments;
import com.espertech.esper.compiler.client.EPCompilerProvider;
import com.espertech.esper.runtime.client.EPRuntimeProvider;

public class Main {
    public static void main(String[] args) throws Exception {
        var compiler = EPCompilerProvider.getCompiler();
        var configuration = new Configuration();

        // create a Thing event type
        configuration.getCommon().addEventType("Thing",
            new String[]{"id", "foo"},
            new Object[]{String.class, String.class}
        );

        var arguments = new CompilerArguments(configuration);
        var module = compiler.parseModule(
                "create window RecentThings#time(30 seconds) (" +
                "  id            string,\n" +
                "  current_thing Thing,\n" +
                "  prev_thing    Thing\n" +
                ");\n" +
                "on Thing as thing\n" +
                "  merge RecentThings as recent where recent.id = thing.id\n" +
                "  when not matched then insert select\n" +
                "    thing.id as id,\n" +
                "    thing    as current_thing,\n" +
                "    thing    as prev_thing\n" +
                "  when matched then update set\n" +
                "    prev_thing    = current_thing,\n" + // it doesn't like this line
                "    current_thing = thing\n" +
                "    where recent.id = thing.id;\n"
        );
        var compiled = compiler.compile(module, arguments);
        var runtime = EPRuntimeProvider.getDefaultRuntime(configuration);
        runtime.getDeploymentService().deploy(compiled);

        var event = new Object[]{"123", "hello"};

        runtime.getEventService().sendEventObjectArray(event, "Thing");
        runtime.getEventService().sendEventObjectArray(event, "Thing");
        runtime.getEventService().sendEventObjectArray(event, "Thing");
    }
}
```

```
[main] INFO com.espertech.esper.runtime.internal.kernel.service.EPRuntimeImpl - Initializing runtime URI 'default' version 8.4.0
[main] ERROR com.espertech.esper.common.internal.settings.ExceptionHandlingService - Exception encountered processing deployment-id '16393719-31e1-407c-af96-f861603072ff' statement 'stmt-1' expression 'on Thing as thing
  merge RecentThings as recent where recent.id = thing.id
  when not matched then insert select
    thing.id as id,
    thing    as current_thing,
    thing    as prev_thing
  when matched then update set
    prev_thing    = current_thing,
    current_thing = thing
    where recent.id = thing.id' : class com.espertech.esper.common.internal.event.arr.ObjectArrayEventBean cannot be cast to class [Ljava.lang.Object; (com.espertech.esper.common.internal.event.arr.ObjectArrayEventBean is in unnamed module of loader 'app'; [Ljava.lang.Object; is in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class com.espertech.esper.common.internal.event.arr.ObjectArrayEventBean cannot be cast to class [Ljava.lang.Object; (com.espertech.esper.common.internal.event.arr.ObjectArrayEventBean is in unnamed module of loader 'app'; [Ljava.lang.Object; is in module java.base of loader 'bootstrap')
	at generated.StatementAIFactoryProvider_173874c44532764542fb45bbf145d3dfceff9bc9_stmt451.m29(StatementAIFactoryProvider_173874c44532764542fb45bbf145d3dfceff9bc9_stmt451.java:325)
	at generated.StatementAIFactoryProvider_173874c44532764542fb45bbf145d3dfceff9bc9_stmt451$6.updateWCopy(ANONYMOUS.java:315)
	at com.espertech.esper.common.internal.epl.ontrigger.InfraOnMergeActionUpd.apply(InfraOnMergeActionUpd.java:63)
	at com.espertech.esper.common.internal.epl.ontrigger.InfraOnMergeMatch.applyNamedWindow(InfraOnMergeMatch.java:52)
	at com.espertech.esper.common.internal.epl.ontrigger.OnExprViewNamedWindowMerge.handleMatching(OnExprViewNamedWindowMerge.java:96)
	at com.espertech.esper.common.internal.epl.ontrigger.OnExprViewNameWindowBase.process(OnExprViewNameWindowBase.java:86)
	at com.espertech.esper.common.internal.epl.ontrigger.OnExprViewNameWindowBase.update(OnExprViewNameWindowBase.java:64)
	at com.espertech.esper.common.internal.view.core.ZeroDepthStreamNoIterate.insert(ZeroDepthStreamNoIterate.java:41)
	at com.espertech.esper.common.internal.context.activator.ViewableActivatorFilter$1.matchFound(ViewableActivatorFilter.java:76)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.processStatementFilterSingle(EPEventServiceImpl.java:796)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.processMatches(EPEventServiceImpl.java:675)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.processWrappedEvent(EPEventServiceImpl.java:453)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.sendEventObjectArray(EPEventServiceImpl.java:378)
	at Main.main(Main.java:42)
[main] ERROR com.espertech.esper.common.internal.settings.ExceptionHandlingService - Exception encountered processing deployment-id '16393719-31e1-407c-af96-f861603072ff' statement 'stmt-1' expression 'on Thing as thing
  merge RecentThings as recent where recent.id = thing.id
  when not matched then insert select
    thing.id as id,
    thing    as current_thing,
    thing    as prev_thing
  when matched then update set
    prev_thing    = current_thing,
    current_thing = thing
    where recent.id = thing.id' : class com.espertech.esper.common.internal.event.arr.ObjectArrayEventBean cannot be cast to class [Ljava.lang.Object; (com.espertech.esper.common.internal.event.arr.ObjectArrayEventBean is in unnamed module of loader 'app'; [Ljava.lang.Object; is in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class com.espertech.esper.common.internal.event.arr.ObjectArrayEventBean cannot be cast to class [Ljava.lang.Object; (com.espertech.esper.common.internal.event.arr.ObjectArrayEventBean is in unnamed module of loader 'app'; [Ljava.lang.Object; is in module java.base of loader 'bootstrap')
	at generated.StatementAIFactoryProvider_173874c44532764542fb45bbf145d3dfceff9bc9_stmt451.m29(StatementAIFactoryProvider_173874c44532764542fb45bbf145d3dfceff9bc9_stmt451.java:325)
	at generated.StatementAIFactoryProvider_173874c44532764542fb45bbf145d3dfceff9bc9_stmt451$6.updateWCopy(ANONYMOUS.java:315)
	at com.espertech.esper.common.internal.epl.ontrigger.InfraOnMergeActionUpd.apply(InfraOnMergeActionUpd.java:63)
	at com.espertech.esper.common.internal.epl.ontrigger.InfraOnMergeMatch.applyNamedWindow(InfraOnMergeMatch.java:52)
	at com.espertech.esper.common.internal.epl.ontrigger.OnExprViewNamedWindowMerge.handleMatching(OnExprViewNamedWindowMerge.java:96)
	at com.espertech.esper.common.internal.epl.ontrigger.OnExprViewNameWindowBase.process(OnExprViewNameWindowBase.java:86)
	at com.espertech.esper.common.internal.epl.ontrigger.OnExprViewNameWindowBase.update(OnExprViewNameWindowBase.java:64)
	at com.espertech.esper.common.internal.view.core.ZeroDepthStreamNoIterate.insert(ZeroDepthStreamNoIterate.java:41)
	at com.espertech.esper.common.internal.context.activator.ViewableActivatorFilter$1.matchFound(ViewableActivatorFilter.java:76)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.processStatementFilterSingle(EPEventServiceImpl.java:796)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.processMatches(EPEventServiceImpl.java:675)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.processWrappedEvent(EPEventServiceImpl.java:453)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.sendEventObjectArray(EPEventServiceImpl.java:378)
	at Main.main(Main.java:43)

Process finished with exit code 0
```

**Comment by icholy** [comment]
@bernhardttom no dice, same issue in 8.4.0

**Comment by icholy** [comment]
Btw, same issue when using Map events

``` java
// create a Thing event type
configuration.getCommon().addEventType("Thing", Map.of(
    "id", String.class,
    "foo", String.class
));
```

``` text
class com.espertech.esper.common.internal.event.map.MapEventBean cannot be cast to class java.util.Map
```

No problem using a regular class for the event type:

``` java
public class Thing {
    private final String id;
    public Thing(String id) {
        this.id = id;
    }
    public String getId() { return id; }
    public String getFoo() { return "foo"; }
}
```

**Comment by icholy** [comment]
Thanks!
