### ISSUE TITLE
Incorrect null-value result of aggregation function when used as parameter to double nested single-row function

### ISSUE THREAD

**Issue by icholy** [espertechinc/esper#186]
When there's more than one nested function call, you can't use the result of an aggregate function as a parameter.

```
select identity(identity(value))       from Thing;" // works
select identity(last(value))           from Thing;" // works
select identity(identity(last(value))) from Thing;" // fails
```

Example:

``` java
import com.espertech.esper.common.client.configuration.Configuration;
import com.espertech.esper.common.client.configuration.compiler.ConfigurationCompilerPlugInSingleRowFunction;
import com.espertech.esper.compiler.client.CompilerArguments;
import com.espertech.esper.compiler.client.EPCompilerProvider;
import com.espertech.esper.runtime.client.EPRuntimeProvider;

import java.util.Map;

public class Main {
    public static void main(String[] args) throws Exception {
        var compiler = EPCompilerProvider.getCompiler();
        var configuration = new Configuration();

        // create a Thing event type
        configuration.getCommon().addEventType("Thing", Map.of("value", Integer.class ));

        // register identity user defined function
        var entry = new ConfigurationCompilerPlugInSingleRowFunction();
        entry.setName("identity");
        entry.setFunctionClassName(Main.class.getCanonicalName());
        entry.setFunctionMethodName("identity");
        entry.setValueCache(ConfigurationCompilerPlugInSingleRowFunction.ValueCache.DISABLED);
        entry.setRethrowExceptions(true);
        configuration.getCompiler().addPlugInSingleRowFunction(entry);

        var arguments = new CompilerArguments(configuration);
        var module = compiler.parseModule(
                "@name('bad') select identity(identity(last(value))) as value from Thing;\n"
        );
        var compiled = compiler.compile(module, arguments);
        var runtime = EPRuntimeProvider.getDefaultRuntime(configuration);
        var deployment = runtime.getDeploymentService().deploy(compiled);

        var stmt = runtime.getDeploymentService().getStatement(deployment.getDeploymentId(), "bad");
        stmt.addListener((newData, oldData, stmt1, runtime1) -> {
            var value = newData[0].get("value");
            System.out.println(String.format("Value: %d", value));
        });

        var event = Map.<String, Object>of( "value", 42 );
        runtime.getEventService().sendEventMap(event, "Thing");
        runtime.getEventService().sendEventMap(event, "Thing");
        runtime.getEventService().sendEventMap(event, "Thing");
    }

    public static Integer identity(Integer value) { return value * value; }
}
```

Exception:

```
[main] INFO com.espertech.esper.runtime.internal.kernel.service.EPRuntimeImpl - Initializing runtime URI 'default' version 8.4.0
[main] ERROR com.espertech.esper.common.internal.epl.expression.dot.core.ExprDotNodeForgeStaticMethodEval - Invocation exception when invoking method 'identity' of class 'Main' passing parameters [null] for statement 'bad': NullPointerException : null
java.lang.NullPointerException
	at Main.identity(Main.java:42)
	at generated.ResultSetProcessorFactoryProvider_29603e5045a23345422b45906345ae2a08d614ec_bad$SelectExprProcessorImpl.m3(SelectExprProcessorImpl.java:348)
	at generated.ResultSetProcessorFactoryProvider_29603e5045a23345422b45906345ae2a08d614ec_bad$SelectExprProcessorImpl.m2(SelectExprProcessorImpl.java:332)
	at generated.ResultSetProcessorFactoryProvider_29603e5045a23345422b45906345ae2a08d614ec_bad$SelectExprProcessorImpl.m1(SelectExprProcessorImpl.java:326)
	at generated.ResultSetProcessorFactoryProvider_29603e5045a23345422b45906345ae2a08d614ec_bad$SelectExprProcessorImpl.m0(SelectExprProcessorImpl.java:318)
	at generated.ResultSetProcessorFactoryProvider_29603e5045a23345422b45906345ae2a08d614ec_bad$SelectExprProcessorImpl.process(SelectExprProcessorImpl.java:311)
	at com.espertech.esper.common.internal.epl.resultset.handthru.ResultSetProcessorHandThroughUtil.getSelectEventsNoHavingHandThruView(ResultSetProcessorHandThroughUtil.java:45)
	at generated.ResultSetProcessorFactoryProvider_29603e5045a23345422b45906345ae2a08d614ec_bad$RSP.processViewResult(RSP.java:125)
	at generated.OutputProcessViewFactoryProvider_29603e5045a23345422b45906345ae2a08d614ec_bad$OPV.update(OPV.java:65)
	at com.espertech.esper.common.internal.view.core.ZeroDepthStreamNoIterate.insert(ZeroDepthStreamNoIterate.java:41)
	at com.espertech.esper.common.internal.context.activator.ViewableActivatorFilter$1.matchFound(ViewableActivatorFilter.java:76)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.processStatementFilterSingle(EPEventServiceImpl.java:796)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.processMatches(EPEventServiceImpl.java:675)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.processWrappedEvent(EPEventServiceImpl.java:453)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.sendEventMap(EPEventServiceImpl.java:395)
	at Main.main(Main.java:39)
[main] ERROR com.espertech.esper.common.internal.settings.ExceptionHandlingService - Exception encountered processing deployment-id 'ce0291d4-4c03-4cdf-9c59-56469e60c0db' statement 'bad' expression '@name('bad') select identity(identity(last(value))) as value from Thing' : Invocation exception when invoking method 'identity' of class 'Main' passing parameters [null] for statement 'bad': NullPointerException : null
com.espertech.esper.common.client.EPException: Invocation exception when invoking method 'identity' of class 'Main' passing parameters [null] for statement 'bad': NullPointerException : null
	at com.espertech.esper.common.internal.epl.expression.dot.core.ExprDotNodeForgeStaticMethodEval.staticMethodEvalHandleInvocationException(ExprDotNodeForgeStaticMethodEval.java:230)
	at generated.ResultSetProcessorFactoryProvider_29603e5045a23345422b45906345ae2a08d614ec_bad$SelectExprProcessorImpl.m3(SelectExprProcessorImpl.java:353)
	at generated.ResultSetProcessorFactoryProvider_29603e5045a23345422b45906345ae2a08d614ec_bad$SelectExprProcessorImpl.m2(SelectExprProcessorImpl.java:332)
	at generated.ResultSetProcessorFactoryProvider_29603e5045a23345422b45906345ae2a08d614ec_bad$SelectExprProcessorImpl.m1(SelectExprProcessorImpl.java:326)
	at generated.ResultSetProcessorFactoryProvider_29603e5045a23345422b45906345ae2a08d614ec_bad$SelectExprProcessorImpl.m0(SelectExprProcessorImpl.java:318)
	at generated.ResultSetProcessorFactoryProvider_29603e5045a23345422b45906345ae2a08d614ec_bad$SelectExprProcessorImpl.process(SelectExprProcessorImpl.java:311)
	at com.espertech.esper.common.internal.epl.resultset.handthru.ResultSetProcessorHandThroughUtil.getSelectEventsNoHavingHandThruView(ResultSetProcessorHandThroughUtil.java:45)
	at generated.ResultSetProcessorFactoryProvider_29604e5045a23345422b45906345ae2a08d614ec_bad$RSP.processViewResult(RSP.java:125)
	at generated.OutputProcessViewFactoryProvider_29603e5045a23345422b45906345ae2a08d614ec_bad$OPV.update(OPV.java:65)
	at com.espertech.esper.common.internal.view.core.ZeroDepthStreamNoIterate.insert(ZeroDepthStreamNoIterate.java:41)
	at com.espertech.esper.common.internal.context.activator.ViewableActivatorFilter$1.matchFound(ViewableActivatorFilter.java:76)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.processStatementFilterSingle(EPEventServiceImpl.java:796)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.processMatches(EPEventServiceImpl.java:675)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.processWrappedEvent(EPEventServiceImpl.java:453)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.sendEventMap(EPEventServiceImpl.java:395)
	at Main.main(Main.java:39)
Caused by: java.lang.NullPointerException
	at Main.identity(Main.java:42)
	at generated.ResultSetProcessorFactoryProvider_29603e5045a23345422b45906345ae2a08d614ec_bad$SelectExprProcessorImpl.m3(SelectExprProcessorImpl.java:348)
	... 14 more

Process finished with exit code 0
```

**Note:** if this is a documented limitation, don't hesitate to close this.

**Comment by bernhardttom** [comment]
The NPE is thrown by the function itself, at Main.identity(Main.java:42), fix the function to handle null

**Comment by icholy** [comment]
@bernhardttom the problem is that `Main.identity` should never be receiving a null.

**Comment by bernhardttom** [comment]
change merged to master as VJS-994-99492 aggregation with nested static calls causing UnsupportedOperationException

**Comment by icholy** [comment]
@bernhardttom thanks!
