### ISSUE TITLE
Event type is not an runtime-native event type when using AMQPToObjectCollectorJson 

### ISSUE THREAD

**Issue by DavidCorral94** [espertechinc/esper#187]
Hello,

I've been playing around with Esper Dataflows and, recently, I was trying out the AMQP Input Adapter. According to [AMQPSource Operator](http://esper.espertech.com/release-8.4.0/reference-esperio/html_single/index.html#amqp-source):

> For JSON formatted messages, the adapter provides the AMQPToObjectCollectorJson JSON collector. The collector deserializes the AMQP message bytes into a string using the JVM default encoding and parses the JSON message for processing as an event. You must specify a JSON event type name e.g. create json schema MyJsonEventType(...) and outstream \<MyJsonEventType>.

So, first, I register the json schema into the engine with:
`@public @buseventtype create json schema Dummy (p1 String, p2 Double)`

Secondly, I send the following dataflow EPL code:
```
create dataflow AMQPIncomingDataFlow 
 AMQPSource -> outstream<Dummy> 
 { host: 'localhost', 
   queueName: 'input-spring', 
   collector: {class: 'AMQPToObjectCollectorJson'}, 
   logMessages: true, declareAutoDelete: false } 
EventBusSink(outstream){}
```
It compiles properly, but when I call to the deployment service, it triggers the following exception:
**com.espertech.esper.runtime.client.EPDeployException: Event type 'Dummy' is not an runtime-native event type**
```
com.espertech.esper.runtime.client.EPDeployException: Event type 'Dummy' is not an runtime-native event type
	at com.espertech.esper.runtime.internal.kernel.service.Deployer.deploy(Deployer.java:117)
	at com.espertech.esper.runtime.internal.kernel.service.Deployer.deployFresh(Deployer.java:101)
	at com.espertech.esper.runtime.internal.kernel.service.EPDeploymentServiceImpl.deploy(EPDeploymentServiceImpl.java:90)
	at com.espertech.esper.runtime.internal.kernel.service.EPDeploymentServiceImpl.deploy(EPDeploymentServiceImpl.java:43)
	at utils.EsperUtils.deployNewEventPattern(EsperUtils.java:126)
	at utils.EsperUtils.createDataflow(EsperUtils.java:105)
	at es.uca.smartportcep.CEPController.dataflow(CEPController.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.espertech.esper.common.internal.event.core.EventAdapterException: Event type 'Dummy' is not an runtime-native event type
	at com.espertech.esper.common.internal.event.core.EventTypeUtility.getAdapterFactoryForType(EventTypeUtility.java:1782)
	at com.espertech.esper.runtime.internal.dataflow.op.eventbussink.EventBusSinkFactory.initializeFactory(EventBusSinkFactory.java:35)
	at com.espertech.esper.common.internal.context.aifactory.createdataflow.StatementAgentInstanceFactoryCreateDataflow.ready(StatementAgentInstanceFactoryCreateDataflow.java:42)
	at com.espertech.esper.runtime.internal.kernel.service.Deployer.initStatement(Deployer.java:800)
	at com.espertech.esper.runtime.internal.kernel.service.Deployer.deploySafe(Deployer.java:379)
	at com.espertech.esper.runtime.internal.kernel.service.Deployer.deploy(Deployer.java:113)
	... 56 more
```

This is very weird, because it only happens when using `create json schema`. If I specified none or `map`, there are no exceptions but then I have another exception when serializing because the event type received is not JSON, is Dummy 🙃:
**Exception encountered running data flow 'AMQPIncomingDataFlow': Expected a JSON event type but received Dummy**
```
Exception in thread "Thread-8" com.espertech.esper.common.client.dataflow.core.EPDataFlowExecutionException: Exception encountered running data flow 'AMQPIncomingDataFlow': Expected a JSON event type but received Dummy
	at com.espertech.esper.common.internal.epl.dataflow.core.EPDataFlowInstanceImpl.run(EPDataFlowInstanceImpl.java:101)
	at utils.EsperUtils.lambda$createDataflow$0(EsperUtils.java:110)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.espertech.esper.common.client.EPException: Expected a JSON event type but received Dummy
	at utils.AMQPSerializerJSON.init(AMQPSerializerJSON.java:28)
	at utils.AMQPSerializerJSON.collect(AMQPSerializerJSON.java:19)
	at com.espertech.esperio.amqp.AMQPSource.next(AMQPSource.java:136)
	at com.espertech.esper.common.internal.epl.dataflow.runnables.GraphSourceRunnable.runLoop(GraphSourceRunnable.java:97)
	at com.espertech.esper.common.internal.epl.dataflow.runnables.GraphSourceRunnable.runSync(GraphSourceRunnable.java:75)
	at com.espertech.esper.common.internal.epl.dataflow.core.EPDataFlowInstanceImpl.run(EPDataFlowInstanceImpl.java:93)
	... 2 more
```

Am I doing something wrong in my EPL code? How can I solve this situation and use JSON messages with AMQP dataflows?

Thanks in advance!

**Comment by bernhardttom** [comment]
JSON is a special case as the compiler generates the JSON parser code. There seems to be an issue with AMQP not seeing the type.

**Comment by DavidCorral94** [comment]
Hello @bernhardttom 

Thanks, for the answer, I will be around to follow the bug/issue. In the meantime, I have overcome this problem with these steps:

1. First, we register the schema but not as JSON:
```
@public @buseventtype create schema Dummy as (p1 String, p2 Double)
```
2. Second, we initialize the AMQP dataflow using a custom serializer:
```
create dataflow AMQPIncomingDataFlow 
 AMQPSource -> outstream<Dummy> 
 { host: 'localhost', 
   queueName: 'input-spring', 
   collector: {class: 'AMQPSerializer'}, 
   logMessages: true, declareAutoDelete: false } 
EventBusSink(outstream){}
```
3. The serializer code looks like this:
```
import com.espertech.esperio.amqp.AMQPToObjectCollector;
import com.espertech.esperio.amqp.AMQPToObjectCollectorContext;
import com.google.gson.Gson;

import java.util.Map;

public class AMQPSerializer implements AMQPToObjectCollector {

    @Override
    public void collect(AMQPToObjectCollectorContext context) {
        //System.out.println("Processing Message: " + new String(context.getBytes()));
        Map event = new Gson().fromJson(new String(context.getBytes()), Map.class);

        context.getEmitter().submit(event);
    }
}
```

As you can see, in the serializer we are converting the JSON message to a Map and that Map is what we submit as result. So, thanks to this, we can send event as JSON to the AMQP queue in the meantime.

Hope it can be useful for anyone else!

**Comment by bernhardttom** [comment]
For JSON event types the right value to submit is a JSON formatted String value (and not a Map).

**Comment by bernhardttom** [comment]
The code you provided above and stack trace don't match. There is no "AMQPSerializerJSON.init(AMQPSerializerJSON.java:28)" and there is no AMQPSerializerJSON that EsperIO provides.

**Comment by DavidCorral94** [comment]
Hello,

As I said in my previous comment, it is a workaround in order to be able to send JSON messages using AMQP 0.9.1 and Esper dataflows. Probably is not the best workaround, but it works.

The first comment, the one that opened the issue, is still failing:

> So, first, I register the json schema into the engine with:
>``@public @buseventtype create json schema Dummy (p1 String, p2 Double)``

>Secondly, I send the following dataflow EPL code:

>```
>create dataflow AMQPIncomingDataFlow 
> AMQPSource -> outstream<Dummy> 
> { host: 'localhost', 
 >  queueName: 'input-spring', 
 >  collector: {class: 'AMQPToObjectCollectorJson'}, 
 >  logMessages: true, declareAutoDelete: false } 
>EventBusSink(outstream){}
>```
>It compiles properly, but when I call to the deployment service, it triggers the following exception:
>**com.espertech.esper.runtime.client.EPDeployException: Event type 'Dummy' is not an runtime-native event type**

As you can see, I'm using the default collector class ``AMQPToObjectCollectorJson``, from [Esper IO docs](http://esper.espertech.com/release-8.4.0/reference-esperio/html_single/index.html#amqp-source):

> For JSON formatted messages, the adapter provides the AMQPToObjectCollectorJson JSON collector. The collector deserializes the AMQP message bytes into a string using the JVM default encoding and parses the JSON message for processing as an event. You must specify a JSON event type name e.g. create json schema MyJsonEventType(...) and outstream<MyJsonEventType>.

But this class is not even used because the error happens when deploying the dataflow, so I'm not even able to send a JSON message to the AMQP broker.
