### ISSUE TITLE
The compiler throws a ConcurrentModificationException exception.

### ISSUE THREAD

**Issue by weizn11** [espertechinc/esper#193]
I am running the fire-and-forget query statement in a new thread, but occasionally this error is reported, may I ask if the compiler obtained through EPCompilerProvider.getCompiler() is not thread-safe? Or am I using it incorrectly?
```
504: this.epCompilerArgs.getPath().add(this.epRuntime.getRuntimePath());
505: EPCompiled eplComp = EPCompilerProvider.getCompiler().compileQuery(epl, this.epCompilerArgs);
506: queryEventArray = this.epRuntime.getFireAndForgetService().executeQuery(eplComp).getArray();
```
```
编译EPL语句[select log_id, unix_timestamp, event_data_image, event_data_md5, host_ip, event_data_processid, event_data_direction, event_data_processguid, event_data_user from SysmonNetworkConnectionUniqueWindow where computer_name = 'test.test' and Math.abs(1587555658412 - unix_timestamp) < 15 * 1000 and event_data_sourceip = '192.168.0.1' and event_data_sourceport = 58545 and event_data_destinationip = '192.168.1.1' and event_data_destinationport = 445 and event_data_protocol = 'tcp' order by Math.abs(1587555658412 - unix_timestamp)]失败，异常原因：Failed compiler startup: null
com.espertech.esper.compiler.client.EPCompileException: Failed compiler startup: null
    at com.espertech.esper.compiler.internal.util.CompilerHelperServices.getCompileTimeServices(CompilerHelperServices.java:118)
	at com.espertech.esper.compiler.internal.util.EPCompilerImpl.compileQueryInternal(EPCompilerImpl.java:240)
	at com.espertech.esper.compiler.internal.util.EPCompilerImpl.compileQuery(EPCompilerImpl.java:57)
	at net.weizn.mtata.storm.esper.engine.EsperTaskThread._execute_epl(EsperTaskThread.java:505)
	at net.weizn.mtata.storm.esper.engine.EsperTaskThread._query_process_net(EsperTaskThread.java:310)
	at net.weizn.mtata.storm.esper.engine.EsperTaskThread._exec_task(EsperTaskThread.java:237)
	at net.weizn.mtata.storm.esper.engine.EsperTaskThread.access$100(EsperTaskThread.java:33)
	at net.weizn.mtata.storm.esper.engine.EsperTaskThread$EsperTaskExecuteThread._loop_thread(EsperTaskThread.java:153)
	at net.weizn.mtata.storm.esper.engine.EsperTaskThread$EsperTaskExecuteThread.run(EsperTaskThread.java:186)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.espertech.esper.compiler.internal.util.CompilerHelperServices.getServices(CompilerHelperServices.java:153)
	at com.espertech.esper.compiler.internal.util.CompilerHelperServices.getCompileTimeServices(CompilerHelperServices.java:114)
	... 8 more
```
Thanks in advance!

**Comment by bernhardttom** [comment]
The input to the compiler cannot be modified while the compiler is using it. In this case the path information that the compiler uses appears to get modified by another thread. The code should make sure to not share compiler arguments among other threads.

**Comment by weizn11** [comment]
> 编译器使用编译器时，不能对其进行修改。在这种情况下，编译器使用的路径信息似乎已被另一个线程修改。该代码应确保不要在其他线程之间共享编译器参数。

Indeed that was the cause and the problem has now been solved, thanks!

**Comment by weizn11** [comment]
> The input to the compiler cannot be modified while the compiler is using it. In this case the path information that the compiler uses appears to get modified by another thread. The code should make sure to not share compiler arguments among other threads.

Indeed that was the cause and the problem has now been solved, thanks!
