### ISSUE TITLE
The result of enumeration methods can't be directly used with 'except, union, intersect' enumeration method.

### ISSUE THREAD

**Issue by zhucj1981** [espertechinc/esper#199]
The result of enumeration methods can't be directly used with 'except, union, intersect' enumeration method.

com.espertech.esper.compiler.client.EPCompileException: Failed to validate select-clause expression 'b.except(b)': Enumeration method 'except' requires an expression yielding a collection of values of type 'Object' as input parameter [select b.except(b) from T]
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:149)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compile(CompilerHelperModuleProvider.java:82)
	at com.espertech.esper.compiler.internal.util.EPCompilerImpl.compile(EPCompilerImpl.java:90)
	at Test10.main(Test10.java:44)

```
import java.util.LinkedHashMap;
import java.util.Map;

import com.espertech.esper.common.client.EPCompiled;
import com.espertech.esper.common.client.configuration.Configuration;
import com.espertech.esper.common.client.configuration.compiler.ConfigurationCompilerByteCode;
import com.espertech.esper.common.client.util.EventTypeBusModifier;
import com.espertech.esper.common.client.util.NameAccessModifier;
import com.espertech.esper.compiler.client.CompilerArguments;
import com.espertech.esper.compiler.client.EPCompileException;
import com.espertech.esper.compiler.client.EPCompiler;
import com.espertech.esper.compiler.client.EPCompilerProvider;
import com.espertech.esper.runtime.client.EPDeployment;
import com.espertech.esper.runtime.client.EPRuntime;
import com.espertech.esper.runtime.client.EPRuntimeProvider;

public class Test10 {
	public static void main(String[] args) {
		Map<String, Object> columns = new LinkedHashMap<>();
		columns.put("value", double.class);
		Configuration configuration = new Configuration();
		ConfigurationCompilerByteCode byteCode = configuration.getCompiler().getByteCode();
		byteCode.setAllowSubscriber(true);
		configuration.getCommon().addEventType("bar", columns);
		byteCode.setAccessModifiersPublic();
		CompilerArguments arguments = new CompilerArguments(configuration);

		EPCompiler epCompiler = EPCompilerProvider.getCompiler();
		EPRuntime runtime = EPRuntimeProvider.getDefaultRuntime(configuration);
		try {
			String[] epls = { 
					 "insert into T select {1,2,3}.selectfrom(v=>v) as b from bar",
		                          "select b.except(b) from T",
					};
			String epl = String.join(";", epls);
			epCompiler.compile(epl, arguments);
			Map<String, Object> event = new LinkedHashMap<>();
			event.put("value", 1.0);
			runtime.getEventService().sendEventMap(event, "bar");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}

```

**Comment by bernhardttom** [comment]
Changes for support for parameterized types also fixed this issue

**Comment by zhucj1981** [comment]
Test still failed in 8.6 release.
