### ISSUE TITLE
BigDecimal divide without MathContext

### ISSUE THREAD

**Issue by andyflury** [espertechinc/esper#20]
Hi

Unfortunately there are still three occurrences in Esper 5.2.0 where BidDecimal.divide is used without a MathContext  which leads to

```
java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.
```

These are the locations:
 * com.espertech.esper.epl.agg.aggregator.AggregatorAvgBigDecimal (line 88)
 * com.espertech.esper.type.MathArithTypeEnum (line 501 and 770)

This is an example stack trace:

```
java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.
	at java.math.BigDecimal.divide(BigDecimal.java:1690)
	at com.espertech.esper.type.MathArithTypeEnum$DivideBigDecConvComputer.compute(MathArithTypeEnum.java:770)
	at com.espertech.esper.epl.expression.ops.ExprMathNode.evaluate(ExprMathNode.java:141)
	at com.espertech.esper.epl.core.SelectExprInsertEventBeanFactory$SelectExprInsertNativeWidening.process(SelectExprInsertEventBeanFactory.java:615)
	at com.espertech.esper.epl.core.SelectExprResultProcessor.process(SelectExprResultProcessor.java:58)
	at com.espertech.esper.epl.core.ResultSetProcessorAggregateGrouped.generateOutputEventsView(ResultSetProcessorAggregateGrouped.java:248)
	at com.espertech.esper.epl.core.ResultSetProcessorAggregateGrouped.processViewResult(ResultSetProcessorAggregateGrouped.java:204)
	at com.espertech.esper.epl.view.OutputProcessViewDirect.update(OutputProcessViewDirect.java:48)
	at com.espertech.esper.view.ZeroDepthStreamNoIterate.insert(ZeroDepthStreamNoIterate.java:50)
	at com.espertech.esper.core.context.activator.ViewableActivatorPattern$1.matchFound(ViewableActivatorPattern.java:55)
	at com.espertech.esper.pattern.EvalRootStateNode.evaluateTrue(EvalRootStateNode.java:103)
	at com.espertech.esper.pattern.EvalFollowedByStateNode.evaluateTrue(EvalFollowedByStateNode.java:87)
	at com.espertech.esper.pattern.EvalAndStateNode.evaluateTrue(EvalAndStateNode.java:186)
	at com.espertech.esper.pattern.EvalEveryStateNode.evaluateTrue(EvalEveryStateNode.java:146)
	at com.espertech.esper.pattern.EvalFilterStateNode.evaluateTrue(EvalFilterStateNode.java:80)
	at com.espertech.esper.pattern.EvalFilterStateNode.matchFound(EvalFilterStateNode.java:134)
	at com.espertech.esper.core.service.EPRuntimeImpl.processStatementFilterMultiple(EPRuntimeImpl.java:1235)
	at com.espertech.esper.core.service.EPRuntimeImpl.processMatches(EPRuntimeImpl.java:1070)
```

Thanks
Andy

**Comment by bernhardttom** [comment]
Line 88 in AggregatorAvgBigDecimal is only called if there is no math context provided.
Line 501 in MathArithTypeEnum is not used because DivideBigDecWMathContext would be used instead.
Line 770 in MathArithTypeEnum is a valid observation and must change.
