### ISSUE TITLE
Support for dataflow EventBusSource operator to populate events of implicitly-created wrap event type

### ISSUE THREAD

**Issue by icholy** [espertechinc/esper#208]
The `EventType` for `B` passed to `LogSink` is `WrapperEventType`. 

``` sql
create schema A ( value int );

insert into B select * from A; 

create dataflow OutputFlow
  EventBusSource -> events<B> {}
  LogSink(events) { format: "json" };
```

```
Caused by: com.espertech.esper.common.internal.event.core.EventAdapterException: Event type 'B' is not an runtime-native event type
	at com.espertech.esper.common.internal.event.core.EventTypeUtility.getShellForType(EventTypeUtility.java:107)
	at com.espertech.esper.runtime.internal.dataflow.op.logsink.LogSinkOp.<init>(LogSinkOp.java:50)
	at com.espertech.esper.runtime.internal.dataflow.op.logsink.LogSinkFactory.operator(LogSinkFactory.java:61)
	at com.espertech.esper.common.internal.epl.dataflow.realize.DataflowInstantiator.instantiateOperator(DataflowInstantiator.java:138)
	... 6 more
```

`LogSink` tries to get an instance of `EventBeanSPI`

https://github.com/espertechinc/esper/blob/bac89610fb399c8530921967ed35d3019eb4cf67/runtime/src/main/java/com/espertech/esper/runtime/internal/dataflow/op/logsink/LogSinkOp.java#L50

However, `getShellForType` doesn't check for `WrapperEventType`

https://github.com/espertechinc/esper/blob/bac89610fb399c8530921967ed35d3019eb4cf67/common/src/main/java/com/espertech/esper/common/internal/event/core/EventTypeUtility.java#L89-L106

I figured it would as simple as adding that case, but it seems like `WrapperEventBean` doesn't implement `EventBeanSPI`.

**Comment by icholy** [comment]
For `WrapperEventBean` to implement `EventBeanSPI`, it's underlying `theEvent` would also need to be an `EventSPI` instance. This would break backwards compatibility. One way around this would be to add a separate `WrapperEventBeanSPI` class.

**Comment by icholy** [comment]
Something like this 

``` java

import com.espertech.esper.common.client.EventBean;
import com.espertech.esper.common.client.EventPropertyGetter;
import com.espertech.esper.common.client.EventType;
import com.espertech.esper.common.client.PropertyAccessException;
import com.espertech.esper.common.internal.collection.Pair;
import com.espertech.esper.common.internal.event.core.*;

import java.util.Collections;
import java.util.Map;

public class WrapperEventBeanSPI implements EventBeanSPI, DecoratingEventBean {
    private EventBeanSPI theEvent;
    private Map<String, Object> map = Collections.emptyMap();
    private final EventType eventType;

    public WrapperEventBeanSPI(WrapperEventType eventType) {
        this.theEvent = EventTypeUtility.getShellForType(eventType.getUnderlyingEventType());
        this.eventType = eventType;
    }

    public Object get(String property) throws PropertyAccessException {
        EventPropertyGetter getter = eventType.getGetter(property);
        if (getter == null) {
            throw new PropertyAccessException("Property named '" + property + "' is not a valid property name for this type");
        }
        return eventType.getGetter(property).get(this);
    }

    public EventType getEventType() {
        return eventType;
    }

    public Object getUnderlying() {
        // If wrapper is simply for the underlying with no additional properties, then return the underlying type
        if (map.isEmpty()) {
            return theEvent.getUnderlying();
        } else {
            return new Pair<Object, Map>(theEvent.getUnderlying(), map);
        }
    }

    public Map<String, Object> getDecoratingProperties() {
        return map;
    }

    public EventBean getUnderlyingEvent() {
        return theEvent;
    }

    public String toString() {
        return "WrapperEventBeanSPI " +
                "[event=" + theEvent + "] " +
                "[properties=" + map + "]";
    }

    public Object getFragment(String propertyExpression) {
        EventPropertyGetter getter = eventType.getGetter(propertyExpression);
        if (getter == null) {
            throw PropertyAccessException.notAValidProperty(propertyExpression);
        }
        return getter.getFragment(this);
    }

    @Override
    public void setUnderlying(Object underlying) {
        if (underlying instanceof Pair) {
            Pair<Object, Map> pair = (Pair<Object, Map>) underlying;
            theEvent.setUnderlying(pair.getFirst());
            map = pair.getSecond();
        } else {
            theEvent.setUnderlying(underlying);
            map = Collections.emptyMap();
        }
    }
}
```

**Comment by icholy** [comment]
Alternatively, the existing `WrapperEventBean` could implement `EventBeanSPI` like this.

``` java
    public void setUnderlying(Object underlying) {
        EventBeanSPI event = (EventBeanSPI) theEvent;
        if (underlying instanceof Pair) {
            Pair<Object, Map> pair = (Pair<Object, Map>) underlying;
            event.setUnderlying(pair.getFirst());
            map = pair.getSecond();
        } else {
            event.setUnderlying(underlying);
            map = Collections.emptyMap();
        }
    }

```

**Comment by icholy** [comment]
@bernhardttom should I open a PR with changes proposed in my last comment, or do you want time to look at it yourself?

**Comment by bernhardttom** [comment]
I haven't had a chance to look yet

**Comment by icholy** [comment]
@bernhardttom thanks!
