### ISSUE TITLE
Allow using event property syntax on objects returned by an expression

### ISSUE THREAD

**Issue by icholy** [espertechinc/esper#210]
```
// this works
create variable Thing thing = CreateThing();
create variable String value = thing.value;

// this works
create variable String value = CreateThing().getValue();

// this fails
create variable String value = CreateThing().value;
```

``` java
import com.espertech.esper.common.client.configuration.Configuration;
import com.espertech.esper.compiler.client.CompilerArguments;
import com.espertech.esper.compiler.client.EPCompilerProvider;

public class Main {

    public static class Thing {
        public String getValue() { return "value"; }
    }

    public static Thing CreateThing() { return new Thing(); }

    public static void main(String[] args) throws Exception {

        // read epl file
        var epl = "create variable String thing = CreateThing().value";

        var compiler = EPCompilerProvider.getCompiler();
        var configuration = new Configuration();

        // create a Thing event type
        configuration.getCommon().addImport(Thing.class);
        configuration.getCompiler().addPlugInSingleRowFunction("CreateThing", Main.class.getCanonicalName(), "CreateThing");

        var arguments = new CompilerArguments(configuration);
        var module = compiler.parseModule(epl);
        compiler.compile(module, arguments);
    }
}
```
```
Exception in thread "main" com.espertech.esper.compiler.client.EPCompileException: Failed to validate variable-assignment expression 'CreateThing().CreateThing': Failed to resolve method 'value': Could not find enumeration method, date-time method, instance method or property named 'value' in class 'Main$Thing' taking no parameters [create variable String value = CreateThing().value]
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:149)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compile(CompilerHelperModuleProvider.java:82)
	at com.espertech.esper.compiler.internal.util.EPCompilerImpl.compile(EPCompilerImpl.java:165)
	at Main.main(Main.java:27)
Caused by: com.espertech.esper.compiler.client.EPCompileExceptionItem: Failed to validate variable-assignment expression 'CreateThing().CreateThing': Failed to resolve method 'value': Could not find enumeration method, date-time method, instance method or property named 'value' in class 'Main$Thing' taking no parameters
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:124)
	... 3 more
Caused by: com.espertech.esper.common.internal.compile.stage2.StatementSpecCompileException: Failed to validate variable-assignment expression 'CreateThing().CreateThing': Failed to resolve method 'value': Could not find enumeration method, date-time method, instance method or property named 'value' in class 'Main$Thing' taking no parameters
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:294)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:109)
	... 3 more
Caused by: com.espertech.esper.common.internal.epl.expression.core.ExprValidationException: Failed to validate variable-assignment expression 'CreateThing().CreateThing': Failed to resolve method 'value': Could not find enumeration method, date-time method, instance method or property named 'value' in class 'Main$Thing' taking no parameters
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.makeValidationExWExpression(ExprNodeUtilityValidate.java:152)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtree(ExprNodeUtilityValidate.java:139)
	at com.espertech.esper.common.internal.context.aifactory.createvariable.StmtForgeMethodCreateVariable.make(StmtForgeMethodCreateVariable.java:77)
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:225)
	... 4 more
Caused by: com.espertech.esper.common.internal.epl.expression.core.ExprValidationException: Failed to resolve method 'value': Could not find enumeration method, date-time method, instance method or property named 'value' in class 'Main$Thing' taking no parameters
	at com.espertech.esper.common.internal.epl.expression.dot.core.ExprDotNodeUtility.getChainEvaluators(ExprDotNodeUtility.java:342)
	at com.espertech.esper.common.internal.epl.expression.funcs.ExprPlugInSingleRowNode.validate(ExprPlugInSingleRowNode.java:181)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtreeInternal(ExprNodeUtilityValidate.java:256)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityValidate.getValidatedSubtree(ExprNodeUtilityValidate.java:124)
	... 6 more
Caused by: com.espertech.esper.common.internal.epl.expression.core.ExprValidationException: Failed to resolve method 'value': Could not find enumeration method, date-time method, instance method or property named 'value' in class 'Main$Thing' taking no parameters
	at com.espertech.esper.common.internal.epl.expression.dot.core.ExprDotNodeUtility$1.handle(ExprDotNodeUtility.java:492)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityResolve.resolveMethodAllowWildcardAndStream(ExprNodeUtilityResolve.java:116)
	at com.espertech.esper.common.internal.epl.expression.dot.core.ExprDotNodeUtility.getValidateMethodDescriptor(ExprDotNodeUtility.java:496)
	at com.espertech.esper.common.internal.epl.expression.dot.core.ExprDotNodeUtility.getChainEvaluators(ExprDotNodeUtility.java:325)
	... 9 more
Caused by: com.espertech.esper.common.internal.settings.ClasspathImportException: Could not find enumeration method, date-time method, instance method or property named 'value' in class 'Main$Thing' taking no parameters
	at com.espertech.esper.common.internal.settings.ClasspathImportServiceBase.convert(ClasspathImportServiceBase.java:323)
	at com.espertech.esper.common.internal.settings.ClasspathImportServiceCompileTimeImpl.resolveMethod(ClasspathImportServiceCompileTimeImpl.java:126)
	at com.espertech.esper.common.internal.epl.expression.core.ExprNodeUtilityResolve.resolveMethodAllowWildcardAndStream(ExprNodeUtilityResolve.java:111)
	... 11 more
Caused by: com.espertech.esper.common.internal.util.MethodResolverNoSuchMethodException: Unknown method Thing.value()
	at com.espertech.esper.common.internal.util.MethodResolver.resolveMethod(MethodResolver.java:203)
	at com.espertech.esper.common.internal.settings.ClasspathImportServiceCompileTimeImpl.resolveMethod(ClasspathImportServiceCompileTimeImpl.java:124)
	... 12 more
```

**Comment by bernhardttom** [comment]
There is no such thing as an event property of an object returned by a function

**Comment by icholy** [comment]
@bernhardttom I don't understand what you're saying

```
create variable Thing thing = CreateThing();
create variable String value = thing.value;
```

In this example, the function `CreateThing` returns an object (instance of Thing) and then it correctly resolves the `value` property to the `getValue()` method.

**Comment by bernhardttom** [comment]
Variables can have an event type as the variable type thereby the compiler allows event property syntax, but only for variables

**Comment by icholy** [comment]
Ah ok, so this isn't a bug. Is there a reason property syntax isn't allowed in this case? It seems like the `EventType` for `Thing` would be available to the compiler. The tried out all the event syntax variations and they parse fine, so the grammar doesn't need work. Am I missing something?

**Comment by bernhardttom** [comment]
The most recent version allows chaining array element expressions which wasn't there before. Dynamic properties don't chain.

**Comment by icholy** [comment]
That's a bummer.

**Comment by bernhardttom** [comment]
Correction, dynamic properties do chain for events but for objects they are not currently allowed to chain I think.

**Comment by icholy** [comment]
Is there something (aside from time/effort/complexity) preventing it from being added in the future?

**Comment by bernhardttom** [comment]
not that I can see
