### ISSUE TITLE
NullPointer when using List field in update istream query

### ISSUE THREAD

**Issue by streaming2936** [espertechinc/esper#220]
When inserting an event that has a field of type List via the EventService, you get a NullPointer somewhere in the generated code, if you use that List field with `.anyOf` in an `update istream` statement.

A minimal example:
```
public class EventWithListField implements Serializable {

    private boolean updated;
    private List<Object> listField;

   // Omitted constructor etc
}
```

Compile with the following EPL:
```
        EPCompiled compiled;
        try {
            CompilerArguments arguments = new CompilerArguments(configuration);
            compiled = EPCompilerProvider.getCompiler().compile("update istream EventWithListField set updated = true where listField.anyOf(e -> e is not null)", arguments);
        } catch (EPCompileException ex) {
            throw new RuntimeException(ex);
        }
```

```
        EventWithListField event = new EventWithListField(List.of("Object1", "Object2"));
        runtime.getEventService().sendEventBean(event, event.getClass().getSimpleName());
```

Which results in:
```
Exception in thread "main" java.lang.NullPointerException
	at generated.StatementAIFactoryProvider_d8d7e5af458cac45427e4595574587d889c407d1_stmt450.m8(StatementAIFactoryProvider_d8d7e5af458cac45427e4595574587d889c407d1_stmt450.java:102)
	at generated.StatementAIFactoryProvider_d8d7e5af458cac45427e4595574587d889c407d1_stmt450.m7(StatementAIFactoryProvider_d8d7e5af458cac45427e4595574587d889c407d1_stmt450.java:92)
	at generated.StatementAIFactoryProvider_d8d7e5af458cac45427e4595574587d889c407d1_stmt450.m4(StatementAIFactoryProvider_d8d7e5af458cac45427e4595574587d889c407d1_stmt450.java:75)
	at generated.StatementAIFactoryProvider_d8d7e5af458cac45427e4595574587d889c407d1_stmt450.m3(StatementAIFactoryProvider_d8d7e5af458cac45427e4595574587d889c407d1_stmt450.java:68)
	at generated.StatementAIFactoryProvider_d8d7e5af458cac45427e4595574587d889c407d1_stmt450$1.evaluate(ANONYMOUS.java:57)
	at com.espertech.esper.common.internal.context.util.InternalEventRouterPreprocessor.process(InternalEventRouterPreprocessor.java:96)
	at com.espertech.esper.common.internal.context.util.InternalEventRouterImpl.getPreprocessedEvent(InternalEventRouterImpl.java:144)
	at com.espertech.esper.common.internal.context.util.InternalEventRouterImpl.preprocess(InternalEventRouterImpl.java:71)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.processWrappedEvent(EPEventServiceImpl.java:360)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.sendEventBean(EPEventServiceImpl.java:186)
	at ListMain.main(ListMain.java:44)
```

However, when the event is inserted using an `insert into EventWithListField` statement, the update statement works as expected. Even when the same event is copied with something like `insert into EventWithListField select listField from ManualEventWithListField()`

Tested with Java 11 on Esper 8.6.0

**Comment by bernhardttom** [comment]
Provide a test class please

**Comment by streaming2936** [comment]
I can reproduce the issue when I add the following case to `EPLOtherUpdateIStream.java`

```java

    private static class EPLOtherUpdateIStreamEnumAnyOf implements RegressionExecution {

        @Override
        public void run(RegressionEnvironment env) {
            String epl = "@public @buseventtype create schema MyEvent as " + SupportEventWithListOfObject.class.getName() + ";\n" +
                    "@name('update') update istream MyEvent set updated = true where mylist.anyOf(e -> e is not null); \n" +
                    "@name('s0') select updated from MyEvent;\n";
            env.compileDeploy(epl).addListener("s0");

            env.sendEventBean(new SupportEventWithListOfObject(Arrays.asList("first", "second")), "MyEvent");
            assertTrue((Boolean) env.listener("s0").assertOneGetNewAndReset().get("updated"));
            env.undeployAll();
        }
    }

    public static class SupportEventWithListOfObject implements Serializable{
        private final List<Object> mylist;
        private boolean updated;

        public SupportEventWithListOfObject(List<Object> mylist) {
            this.mylist = mylist;
            this.updated = false;
        }

        public boolean isUpdated() {
            return updated;
        }

        public void setUpdated(boolean updated) {
            this.updated = updated;
        }

        public List<Object> getMylist() {
            return mylist;
        }
    }
```
