### ISSUE TITLE
Tables defined within modules do not work in joins

### ISSUE THREAD

**Issue by liquidalan** [espertechinc/esper#230]
When you have a table defined within a module and that table joins to a stream the runtime throws the following exception:

`java.lang.NullPointerException
	at com.espertech.esper.common.internal.epl.join.exec.hash.IndexedTableLookupStrategyHashedProp.lookup(IndexedTableLookupStrategyHashedProp.java:42)
	at com.espertech.esper.common.internal.epl.join.exec.base.TableLookupExecNodeTableLocking.process(TableLookupExecNodeTableLocking.java:39)
	at com.espertech.esper.common.internal.epl.join.strategy.ExecNodeQueryStrategy.lookup(ExecNodeQueryStrategy.java:53)
	at com.espertech.esper.common.internal.epl.join.base.JoinSetComposerStreamToWinImpl.join(JoinSetComposerStreamToWinImpl.java:112)
	at com.espertech.esper.common.internal.epl.join.base.JoinExecutionStrategyImpl.join(JoinExecutionStrategyImpl.java:54)
	at com.espertech.esper.common.internal.epl.join.base.JoinExecStrategyDispatchable.execute(JoinExecStrategyDispatchable.java:67)
	at com.espertech.esper.common.internal.context.util.EPStatementAgentInstanceHandle.internalDispatch(EPStatementAgentInstanceHandle.java:112)
	at com.espertech.esper.runtime.internal.namedwindow.NamedWindowDispatchServiceImpl.processHandle(NamedWindowDispatchServiceImpl.java:349)
	at com.espertech.esper.runtime.internal.namedwindow.NamedWindowDispatchServiceImpl.processDispatches(NamedWindowDispatchServiceImpl.java:139)
	at com.espertech.esper.runtime.internal.namedwindow.NamedWindowDispatchServiceImpl.dispatch(NamedWindowDispatchServiceImpl.java:90)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.processThreadWorkQueueFront(EPEventServiceImpl.java:447)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.processThreadWorkQueue(EPEventServiceImpl.java:412)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.processWrappedEvent(EPEventServiceImpl.java:388)
	at com.espertech.esper.runtime.internal.kernel.service.EPEventServiceImpl.sendEventJson(EPEventServiceImpl.java:168)
`

this is due to the query plan incorrectly building the key for the index lookup:
The class used is TableLookupIndexReqKey - this key includes the module name in both hascode and equals methods.

However the JoinSetComposerPrototypeGeneral at lines #96/99 creates the keys to be used  without including the module - hence causing the join to fail at runtime with the above exception.

Example EPL File

`
// Declare the name for the module (optional).
module com_test_app;
@public create table Basket(basket_id string primary key, symbol string primary key, weight double);
create window StockReturnWindow#unique(symbol) as select '' as symbol, 0.0 as one_min_return from VWAPrice; 

// fails with the above exception
select basket_id, sum(sr.one_min_return*bask.weight) from Basket as bask, StockReturnWindow as sr where bask.symbol = sr.symbol group by bask.basket_id;
`

**Comment by liquidalan** [comment]
Removing the module declaration allows the code to run

**Comment by bernhardttom** [comment]
The query joins on symbol "bask.symbol = sr.symbol" and thus it wouldn't use an index. I assume there is another EPL that creates the index on symbol?

**Comment by liquidalan** [comment]
Thanks for fixing this so quickly.
