### ISSUE TITLE
Fail to undeploy first insert into statement

### ISSUE THREAD

**Issue by acm19** [espertechinc/esper#237]
I'm using ESPER 8.6.0 and 8.7.0, experiencing the issue in both. I'm trying to deploy 2 insert into statement that insert into the same stream. When I try to undeploy the first of them I get the following precondition not satisfied error:

```
com.espertech.esper.runtime.client.EPUndeployPreconditionException: A precondition is not satisfied: Event type 'stream' cannot be un-deployed as it is referenced by deployment 'Insert-B'
	at com.espertech.esper.runtime.internal.kernel.service.Undeployer.makeException(Undeployer.java:225)
	at com.espertech.esper.runtime.internal.kernel.service.Undeployer.checkDependency(Undeployer.java:218)
	at com.espertech.esper.runtime.internal.kernel.service.Undeployer.checkModulePreconditions(Undeployer.java:68)
	at com.espertech.esper.runtime.internal.kernel.service.EPDeploymentServiceImpl.undeployRemoveInternal(EPDeploymentServiceImpl.java:270)
	at com.espertech.esper.runtime.internal.kernel.service.EPDeploymentServiceImpl.undeploy(EPDeploymentServiceImpl.java:232)
```

Apparently the first insert into creates an event type but I don't understand that's the behaviour from reading [the documentation](http://esper.espertech.com/release-8.7.0/reference-esper/html/epl_clauses.html#epl-insert-into).

Minimal test case to reproduce it:

```java
    @Test
    void test() throws EPCompileException, EPDeployException, EPUndeployException {
        var epCompiler = EPCompilerProvider.getCompiler();
        var configuration = new Configuration();
        ConfigurationCompilerByteCode byteCodeConfig = configuration.getCompiler().getByteCode();
        byteCodeConfig.setAccessModifierEventType(NameAccessModifier.PUBLIC);
        var runtime = (EPRuntimeSPI) EPRuntimeProvider.getRuntime("TEST", configuration);
        runtime.getDeploymentService().deploy(epCompiler.compile("create map schema A as (`prop` java.lang.String)", new CompilerArguments(configuration)), new DeploymentOptions().setDeploymentId("EventType-A"));
        runtime.getDeploymentService().deploy(epCompiler.compile("create map schema B as (`prop` java.lang.String)", new CompilerArguments(configuration)), new DeploymentOptions().setDeploymentId("EventType-B"));
        CompilerArguments eventTypeArgs = new CompilerArguments(configuration);
        eventTypeArgs.getPath().add(runtime.getRuntimePath());
        runtime.getDeploymentService().deploy(epCompiler.compile("insert into stream select current_timestamp as x from A", eventTypeArgs), new DeploymentOptions().setDeploymentId("Insert-A"));
        CompilerArguments insertArgs = new CompilerArguments(configuration);
        insertArgs.getPath().add(runtime.getRuntimePath());
        runtime.getDeploymentService().deploy(epCompiler.compile("insert into stream select current_timestamp as x from B", insertArgs), new DeploymentOptions().setDeploymentId("Insert-B"));
        for (String deploymentIdDependency : runtime.getDeploymentService().getDeployment("Insert-B").getDeploymentIdDependencies()) {
            System.out.println(deploymentIdDependency);
        }
        runtime.getDeploymentService().undeploy("Insert-A");
    }
```

Looks like a bug to me, but if it's not, what would be the correct way to deploy these statements so they don't depend on each other.

**Comment by bernhardttom** [comment]
"Insert-A" allocated a new event type "stream" that "Insert-B" depends on. Use "create schema stream(...)" so that "Insert-A" doesn't need to allocate the "stream"event type.
