### ISSUE TITLE
 NullPointerException for filter with global expression in context-partitioned stmt

### ISSUE THREAD

**Issue by BGoldman1989** [espertechinc/esper#24]
Version: 5.2.0

When the EPAdministrator attempts to parse a statement that refers to a declared context and contains one or more aliases to a global expression, a NullPointerException is thrown with the following stack-trace:

```
at com.espertech.esper.core.context.mgr.ContextPropertyRegistryImpl.isContextPropertyPrefix(ContextPropertyRegistryImpl.java:57)
      at com.espertech.esper.epl.declexpr.ExprDeclaredNodeImpl.<init>(ExprDeclaredNodeImpl.java:68)
      at com.espertech.esper.epl.declexpr.ExprDeclaredHelper.getExistsDeclaredExpr(ExprDeclaredHelper.java:37)
      at com.espertech.esper.epl.parse.EPLTreeWalkerListener.exitEventProperty(EPLTreeWalkerListener.java:1443)
      at com.espertech.esper.epl.generated.EsperEPL2GrammarParser$EventPropertyContext.exitRule(EsperEPL2GrammarParser.java:17573)
      at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:71)
      at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:54)
      at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
      at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
      at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
      ...
      at com.espertech.esper.epl.parse.ParseHelper.walk(ParseHelper.java:56)
      at com.espertech.esper.core.service.EPAdministratorHelper.compileEPL(EPAdministratorHelper.java:108)
      at com.espertech.esper.core.service.EPAdministratorHelper.compileEPL(EPAdministratorHelper.java:72)
      at com.espertech.esper.core.service.EPAdministratorImpl.createEPLStmt(EPAdministratorImpl.java:116)
      at com.espertech.esper.core.service.EPAdministratorImpl.createEPL(EPAdministratorImpl.java:66)
```

For example, say I have the following statements:

Global Expression:
`create expression TESTEXPR alias for {a='foo' and b='bar'}`

Context Declaration:
```
create context context1 
    initiated @now and pattern[every(TestEvent(TESTEXPR))] 
    terminated after 10 minutes
```

Statement referring to Context Declaration and Global Expression:
```
context context1 
select * from pattern[every(e1=TestEvent(TESTEXPR) -> e2=TestEvent(a='hello'))]
```

The engine will fail to parse the third statement and will throw the error shown above.  This will happen regardless of whether or not the context declaration contains an alias to a global expression.  I’ve included a test class below that replicates the issue:

```java

import static org.junit.Assert.assertEquals;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import com.espertech.esper.client.Configuration;
import com.espertech.esper.client.EPServiceProvider;
import com.espertech.esper.client.EPServiceProviderManager;
import com.espertech.esper.client.EventBean;
import com.espertech.esper.client.UpdateListener;

public class EsperContextTest {

      private EPServiceProvider epServiceProvider;
      private TestEvent[] events;

      @Before
      public void setUp() throws Exception {

            // Configure EPServiceProvider
            Configuration config = new Configuration();
            config.addEventType("TestEvent", TestEvent.class);
            config.getEngineDefaults().getExecution().setPrioritized(true);
            config.getEngineDefaults().getLogging().setEnableExecutionDebug(false);
            config.getEngineDefaults().getLogging().setEnableQueryPlan(false);
            config.getEngineDefaults().getLogging().setEnableTimerDebug(false);
            config.getEngineDefaults().getMetricsReporting()
                        .setEnableMetricsReporting(false);
            epServiceProvider = EPServiceProviderManager.getDefaultProvider(config);

            // Add global Expression
            epServiceProvider.getEPAdministrator().createEPL(
                        "create expression TESTEXPR alias for {a='foo' and b='bar'}");

            // Test Events
            TestEvent e1 = new TestEvent("fizz", "bang", "buzz");
            TestEvent e2 = new TestEvent("foo", "bar", "buzz");
            TestEvent e3 = new TestEvent("hello", "world", "foo");

            events = new TestEvent[] { e1, e2, e3 };

      }

      // Test context declaration and statement w/ no global expression aliases (passes)
      @Test
      public void testNoGlobalExpressions() {
            String context = "create context context1 initiated @now and pattern[every(TestEvent(a='foo' and b='bar'))] terminated after 10 minutes";
            String statement = "context context1 select * from pattern[every(e1=TestEvent(a='foo' and b='bar') -> e2=TestEvent(a='hello'))]";
            createContextAndStatement(context, statement);
            sendEvents();
      }

      // Test context declaration and statement w/ global expression aliases (fails)
      @Test
      public void testGlobalExpressions() {
            String context = "create context context2 initiated @now and pattern[every(TestEvent(TESTEXPR))] terminated after 10 minutes";
            String statement = "context context2 select * from pattern[every(e1=TestEvent(TESTEXPR) -> e2=TestEvent(a='hello'))]";
            createContextAndStatement(context, statement);
            sendEvents();
      }

      // Test context declaration w/ global expression alias and statement w/ no
      // global expression alias (passes)
      @Test
      public void testContextGlobalExpression() {
            String context = "create context context2 initiated @now and pattern[every(TestEvent(TESTEXPR))] terminated after 10 minutes";
            String statement = "context context2 select * from pattern[every(e1=TestEvent(a='foo' and b='bar') -> e2=TestEvent(a='hello'))]";
            createContextAndStatement(context, statement);
            sendEvents();
      }

      // Test context declaration w/ no global expression alias and statement w/
      // global expression alias (fails)
      @Test
      public void testStatementGlobalExpressions() {
            String context = "create context context1 initiated @now and pattern[every(TestEvent(a='foo' and b='bar'))] terminated after 10 minutes";
            String statement = "context context1 select * from pattern[every(e1=TestEvent(TESTEXPR) -> e2=TestEvent(a='hello'))]";
            createContextAndStatement(context, statement);
            sendEvents();
      }

      // Add statement w/ corresponding context partition to the Esper engine.
      private void createContextAndStatement(String context, String statement) {
            epServiceProvider.getEPAdministrator().createEPL(context);
            epServiceProvider.getEPAdministrator().createEPL(statement)
                        .addListener(new TestListener());
      }

      // Send events to Esper engine
      private void sendEvents() {
            for (TestEvent event : events) {
                  epServiceProvider.getEPRuntime().sendEvent(event);
            }
      }

      // Reset EPServiceProvider for each test
      @After
      public void reset() {
            epServiceProvider.destroy();
      }

      private static class TestEvent {

            private String a;

            private String b;

            private String c;

            public TestEvent(String a, String b, String c) {
                  this.a = a;
                  this.b = b;
                  this.c = c;
            }

            public String getA() {
                  return a;
            }

            public void setA(String a) {
                  this.a = a;
            }

            public String getB() {
                  return b;
            }

            public void setB(String b) {
                  this.b = b;
            }

            public String getC() {
                  return c;
            }

            public void setC(String c) {
                  this.c = c;
            }

            public String toString() {
                  return "(" + a + "," + b + "," + c + ")";
            }
      }

      private static class TestListener implements UpdateListener {

            @Override
            public void update(EventBean[] newEvents, EventBean[] oldEvents) {
                  EventBean event = newEvents[0];
                  TestEvent e1 = (TestEvent) event.get("e1");
                  TestEvent e2 = (TestEvent) event.get("e2");

                  assertEquals(e1.toString(), "(foo,bar,buzz)");
                  assertEquals(e2.toString(), "(hello,world,foo)");
            }
      }

}
```
Thanks

**Comment by bernhardttom** [comment]
merged change into master for 5.4 release
