### ISSUE TITLE
Compilation error during runtime

### ISSUE THREAD

**Issue by mohitanchlia** [espertechinc/esper#253]
I am trying to run some examples but seeing this error:

java.lang.RuntimeException: com.espertech.esper.compiler.client.EPCompileException: Unexpected exception compiling module: org.codehaus.janino.Parser.parseAbstractCompilationUnit()Lorg/codehaus/janino/Java$AbstractCompilationUnit;
	at org.example.NamedWindowQueryMain.compileDeploy(NamedWindowQueryMain.java:179)
	at org.example.NamedWindowQueryMain.runExample(NamedWindowQueryMain.java:76)
	at org.example.NamedWindowQueryMain.main(NamedWindowQueryMain.java:37)
Caused by: com.espertech.esper.compiler.client.EPCompileException: Unexpected exception compiling module: org.codehaus.janino.Parser.parseAbstractCompilationUnit()Lorg/codehaus/janino/Java$AbstractCompilationUnit;
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compile(CompilerHelperModuleProvider.java:93)
	at com.espertech.esper.compiler.internal.util.EPCompilerImpl.compile(EPCompilerImpl.java:98)
	at org.example.NamedWindowQueryMain.compileDeploy(NamedWindowQueryMain.java:175)
	... 2 more
Caused by: java.lang.NoSuchMethodError: org.codehaus.janino.Parser.parseAbstractCompilationUnit()Lorg/codehaus/janino/Java$AbstractCompilationUnit;
	at com.espertech.esper.compiler.internal.util.JaninoCompiler.compileInternal(JaninoCompiler.java:87)
	at com.espertech.esper.compiler.internal.util.JaninoCompiler.compile(JaninoCompiler.java:36)
	at com.espertech.esper.compiler.internal.util.CompilerPool.submit(CompilerPool.java:52)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:135)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compile(CompilerHelperModuleProvider.java:89)
	... 4 more

**Comment by bernhardttom** [comment]
This indicates your classpath is incorrect. Check the version on all the jar files making sure they match the Esper doc or Maven for that version.
