### ISSUE TITLE
NPE when try to load EPL with pattern syntax

### ISSUE THREAD

**Issue by luxiaoxun** [espertechinc/esper#257]
esper version: 7.1.0
When I try to init runtime with 4 rules,  rule NO.4 failed, Can anyone help?  thanks.
```
java.lang.NullPointerException
	at org.antlr.v4.runtime.ANTLRInputStream.<init>(ANTLRInputStream.java:45)
	at com.espertech.esper.epl.parse.CaseInsensitiveInputStream.<init>(CaseInsensitiveInputStream.java:55)
	at com.espertech.esper.epl.parse.ParseHelper.parse(ParseHelper.java:82)
	at com.espertech.esper.core.service.EPAdministratorHelper.compileEPL(EPAdministratorHelper.java:84)
	at com.espertech.esper.core.service.EPAdministratorHelper.compileEPL(EPAdministratorHelper.java:67)
	at com.espertech.esper.core.service.EPAdministratorImpl.createEPLStmt(EPAdministratorImpl.java:104)
	at com.espertech.esper.core.service.EPAdministratorImpl.createEPL(EPAdministratorImpl.java:83)
	at com.luxx.test.EsperTest.init(EsperTest.java:45)
	at com.luxx.test.EsperTest.testEpl(EsperTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

```

My test code:
```
public class EsperTest {

    private String name = "LogDataEventEngine";
    private String eventType = "LogDataEvent";

    private EPServiceProvider epServiceProvider;

    @Test
    public void testEpl() {
        Map<String, Object> defaultSchema = new HashMap<>();
        defaultSchema.put("quality", Integer.class);
        defaultSchema.put("from_ip", String.class);
        defaultSchema.put("to_ip", String.class);

        Configuration configuration = new Configuration();
        configuration.setPatternMaxSubexpressions(100000L);
        configuration.getEngineDefaults().getThreading().setListenerDispatchPreserveOrder(true);
        configuration.addEventType(eventType, defaultSchema);

        epServiceProvider = EPServiceProviderManager.getProvider(this.name, configuration);

        List<Rule> rules = loadAllRules();
        StatementAwareUpdateListener listener = new StatementAwareUpdateListener() {
            @Override
            public void update(EventBean[] eventBeans, EventBean[] eventBeans1, EPStatement epStatement, EPServiceProvider epServiceProvider) {
            }
        };
        init(rules, listener);
    }

    private void init(List<Rule> rules, StatementAwareUpdateListener listener) {
        if (rules != null && rules.size() > 0) {
            for (Rule rule : rules) {
                epServiceProvider.getEPAdministrator()
                        .createEPL(rule.getStatement(), rule.getName(), rule.getId())
                        .addListener(listener);
            }
        }
    }

    private List<Rule> loadAllRules() {
        List<Rule> rules = new ArrayList<>();
        Rule rule1 = new Rule();
        rule1.setId(1);
        rule1.setName("rule1");
        rule1.setStatement("select * from LogDataEvent(from_ip='172.17.6.101')");
        rules.add(rule1);

        Rule rule2 = new Rule();
        rule2.setId(2);
        rule2.setName("rule2");
        rule2.setStatement("select * from LogDataEvent(quality>=5)");
        rules.add(rule2);

        Rule rule3 = new Rule();
        rule3.setId(3);
        rule3.setName("rule3");
        rule3.setStatement("select to_ip,count(*) from LogDataEvent#time_batch(10 seconds) group by to_ip having count(*) > 8");
        rules.add(rule3);

         // Failed EPL rule
        Rule rule4 = new Rule();
        rule3.setId(4);
        rule3.setName("rule4");
        rule3.setStatement("select * from pattern [every a=LogDataEvent(to_ip='172.17.6.109') -> b=LogDataEvent(from_ip=a.from_ip)]");
        rules.add(rule4);

        return rules;
    }
}
```

**Comment by luxiaoxun** [comment]
Oh, I should use 'UpdateListener' to the pattern statement.
