### ISSUE TITLE
Error parsing JSON schema with complex property

### ISSUE THREAD

**Issue by AhmedAwad** [espertechinc/esper#258]
I have the following declarations in an .epl file

```
create schema Objects as (tracking_id int, class_id int, class_name string, confidence double, bbox_xywh int[], rois string[], lc string[], rois_oc string[]);

create map schema CountMap as (obj string, cnt int);

create  schema Analytics as ( obj_count_rois CountMap, overcrowded_rois string[], lc_cum_count CountMap, lc_curr_count CountMap);


create  schema FrameMeta as (frame_num int, source_id int, frame_width int, frame_height int, raw_time long, timestamp string, analytics Analytics);


create json schema IdentifiedFrames as ( frame_meta FrameMeta,  Objects_meta Objects[]);
```
I am declaring ```IdentifiedFrames``` as a JSON schema because I will receive the data as JSON objects.

When I run the following code to compile the above code as a module,
```
Configuration config = new Configuration();
        config.getRuntime().getExecution().setPrioritized(true);
        config.getRuntime().getThreading().setInternalTimerEnabled(false);
        config.getCompiler().getByteCode().setBusModifierEventType(EventTypeBusModifier.BUS);
        config.getCompiler().getByteCode().setAccessModifiersPublic();
//        config.getCommon().getEventMeta().setDefaultEventRepresentation(EventUnderlyingType.JSON);
        EPRuntime runtime = EPRuntimeProvider.getDefaultRuntime(config);
        runtime.initialize();
        try
        {
            EPCompiler compiler = EPCompilerProvider.getCompiler();
            InputStream inputFile = Runner2.class.getClassLoader().getResourceAsStream("etc/LeftObject.epl");
            if (inputFile == null)
            {
                inputFile = new FileInputStream("C:\\Work\\DSG\\DeepCEP\\src\\etc\\LeftObject.epl");
            }
            Module module = compiler.readModule(inputFile, "LeftObject.epl");

            CompilerArguments compArgs = new CompilerArguments(config);
            EPCompiled compiled = compiler.compile(module, compArgs);
            runtime.getDeploymentService().deploy(compiled, new DeploymentOptions().setDeploymentId("leftObject"));
}
        catch (EPCompileException ex)
        {
            ex.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ParseException e) {
            e.printStackTrace();
        } catch (EPDeployException e) {
            e.printStackTrace();
        }
```

I get the following exception
```
com.espertech.esper.compiler.client.EPCompileException: Unsupported type '[Ljava.util.Objects;' for property 'Objects_meta' (use @JsonSchemaField to declare additional information) [//@JsonSchemaField(name=Objects_meta, adapter=Objects)  create json schema IdentifiedFrames as ( frame_meta FrameMeta,  Objects_meta Objects[])]
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:172)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compile(CompilerHelperModuleProvider.java:89)
	at com.espertech.esper.compiler.internal.util.EPCompilerImpl.compile(EPCompilerImpl.java:173)
	at org.aeyetech.deepcep.leftobject.Runner2.main(Runner2.java:44)
Caused by: com.espertech.esper.compiler.client.EPCompileExceptionItem: Unsupported type '[Ljava.util.Objects;' for property 'Objects_meta' (use @JsonSchemaField to declare additional information)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:147)
	... 3 more
Caused by: com.espertech.esper.common.internal.compile.stage2.StatementSpecCompileException: Unsupported type '[Ljava.util.Objects;' for property 'Objects_meta' (use @JsonSchemaField to declare additional information)
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:315)
	at com.espertech.esper.compiler.internal.util.CompilerHelperModuleProvider.compileToBytes(CompilerHelperModuleProvider.java:127)
	... 3 more
Caused by: com.espertech.esper.common.internal.epl.expression.core.ExprValidationException: Unsupported type '[Ljava.util.Objects;' for property 'Objects_meta' (use @JsonSchemaField to declare additional information)
	at com.espertech.esper.common.internal.context.aifactory.createschema.StmtForgeMethodCreateSchema.handleCreateSchema(StmtForgeMethodCreateSchema.java:93)
	at com.espertech.esper.common.internal.context.aifactory.createschema.StmtForgeMethodCreateSchema.make(StmtForgeMethodCreateSchema.java:58)
	at com.espertech.esper.compiler.internal.util.CompilerHelperStatementProvider.compileItem(CompilerHelperStatementProvider.java:230)
	... 4 more
Caused by: java.lang.UnsupportedOperationException: Unsupported type '[Ljava.util.Objects;' for property 'Objects_meta' (use @JsonSchemaField to declare additional information)
	at com.espertech.esper.common.internal.event.json.parser.forge.JsonForgeFactoryBuiltinClassTyped.getUnsupported(JsonForgeFactoryBuiltinClassTyped.java:369)
	at com.espertech.esper.common.internal.event.json.parser.forge.JsonForgeFactoryBuiltinClassTyped.forge(JsonForgeFactoryBuiltinClassTyped.java:296)
	at com.espertech.esper.common.internal.event.json.compiletime.JsonEventTypeUtility.computeValueForges(JsonEventTypeUtility.java:321)
	at com.espertech.esper.common.internal.event.json.compiletime.JsonEventTypeUtility.makeJsonTypeCompileTimeNewType(JsonEventTypeUtility.java:122)
	at com.espertech.esper.common.internal.event.core.EventTypeUtility.createNonVariantType(EventTypeUtility.java:1633)
	at com.espertech.esper.common.internal.context.aifactory.createschema.StmtForgeMethodCreateSchema.handleCreateSchema(StmtForgeMethodCreateSchema.java:87)
	... 6 more
```

Following the suggestion to use #JsonSchemaField is also problematic as it seems that I have to declare the ```Objects``` event type as a class. Is there a way to allow using declared types as types for fields in other schemas?

**Comment by bernhardttom** [comment]
I think all the types should be "create json schema " since they become part of a json schema?

**Comment by AhmedAwad** [comment]
Even when I put them all as JSON I am still having the same error.

**Comment by bernhardttom** [comment]
I'd start by renaming the "Objects" event type as "java.util.Objects" is actually a Java class

**Comment by AhmedAwad** [comment]
Wow! This solved the problem and by explicitly setting all other schemas as json.

Thanks a lot! :)
