### ISSUE TITLE
NullPointerException with wrong On-select syntax

### ISSUE THREAD

**Issue by jheusser** [espertechinc/esper#26]
Deploying a module with
```sql
on Event
select 1;
```

fails with the NullPointerException below, in Esper 5.2

```
Caused by: java.lang.NullPointerException
	at com.espertech.esper.core.service.StatementLifecycleSvcUtil.isWritesToTables(StatementLifecycleSvcUtil.java:235)
	at com.espertech.esper.core.service.StatementLifecycleSvcImpl.createStopped(StatementLifecycleSvcImpl.java:264)
	at com.espertech.esper.core.service.StatementLifecycleSvcImpl.createStoppedAssignName(StatementLifecycleSvcImpl.java:194)
	at com.espertech.esper.core.service.StatementLifecycleSvcImpl.createAndStart(StatementLifecycleSvcImpl.java:148)
	at com.espertech.esper.core.service.EPAdministratorImpl.createEPLStmt(EPAdministratorImpl.java:117)
	at com.espertech.esper.core.service.EPAdministratorImpl.createEPL(EPAdministratorImpl.java:91)
	at com.espertech.esper.core.deploy.EPDeploymentAdminImpl.deployInternal(EPDeploymentAdminImpl.java:174)
	at com.espertech.esper.core.deploy.EPDeploymentAdminImpl.deploy(EPDeploymentAdminImpl.java:102)
```

**Comment by bernhardttom** [comment]
changes merged into master for 5.4 release
