### ISSUE TITLE
NPE when accessing table from expression

### ISSUE THREAD

**Issue by dmekhanikov** [espertechinc/esper#30]
When running the following class:

```java
import com.espertech.esper.client.EPRuntime;
import com.espertech.esper.client.EPServiceProvider;
import com.espertech.esper.client.EPServiceProviderManager;
import com.espertech.esper.client.deploy.DeploymentException;
import com.espertech.esper.client.deploy.Module;
import com.espertech.esper.client.deploy.ParseException;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class EsperBreaker {
    public static void main(String ... args) throws ParseException, DeploymentException, IOException {
        EPServiceProvider epService = EPServiceProviderManager.getDefaultProvider();
        EPRuntime runtime = epService.getEPRuntime();

        Module module = epService.getEPAdministrator().getDeploymentAdmin().parse(
                "create schema OrderIssue(id string, instrumentId string);\n" +
                "create window Positions.win:keepall() as (id string, instrumentId string, instrumentName string);\n" +
                "create table Instruments(id string primary key, name string);\n" +
                "create expression getInstrumentName {o => Instruments[o.instrumentId].name};\n" +
                "on OrderIssue oi\n" +
                "insert into Positions(id, instrumentId, instrumentName)\n" +
                "    select id, instrumentId, getInstrumentName(oi);"
        );
        epService.getEPAdministrator().getDeploymentAdmin().deploy(module, null);

        runtime.executeQuery("insert into Instruments(id, name) values ('1', 'EUR/USD')");

        Map<String, Object> orderIssue = new HashMap<>();
        orderIssue.put("id", "1");
        orderIssue.put("instrumentId", "1");
        runtime.sendEvent(orderIssue, "OrderIssue");
    }
}
```
NPE is thrown:
```
ERROR c.e.e.c.s.ExceptionHandlingService - Exception encountered processing statement '1de7f8ec-b203-40e8-8a94-1b6980214948' statement text 'on OrderIssue oi
insert into Positions(id, instrumentId, instrumentName)
    select id, instrumentId, getInstrumentName(oi)' : null
java.lang.NullPointerException: null
	at com.espertech.esper.epl.expression.table.ExprTableAccessNodeSubprop.evaluate(ExprTableAccessNodeSubprop.java:78) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.epl.declexpr.ExprDeclaredEvalBase.evaluate(ExprDeclaredEvalBase.java:84) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.epl.core.eval.EvalBaseMap.process(EvalBaseMap.java:48) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.epl.core.SelectExprResultProcessor.process(SelectExprResultProcessor.java:65) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.epl.core.ResultSetProcessorHandThrough.getSelectEventsNoHaving(ResultSetProcessorHandThrough.java:99) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.epl.core.ResultSetProcessorHandThrough.processViewResult(ResultSetProcessorHandThrough.java:72) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.view.internal.RouteResultViewHandlerFirst.handle(RouteResultViewHandlerFirst.java:91) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.view.internal.RouteResultView.update(RouteResultView.java:84) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.view.ZeroDepthStreamNoIterate.insert(ZeroDepthStreamNoIterate.java:50) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.core.context.activator.ViewableActivatorFilterProxy$2.matchFound(ViewableActivatorFilterProxy.java:101) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.core.service.EPRuntimeImpl.processStatementFilterSingle(EPRuntimeImpl.java:1245) [esper-5.2.0.jar:na]
	at com.espertech.esper.core.service.EPRuntimeImpl.processMatches(EPRuntimeImpl.java:1031) [esper-5.2.0.jar:na]
	at com.espertech.esper.core.service.EPRuntimeImpl.processWrappedEvent(EPRuntimeImpl.java:482) [esper-5.2.0.jar:na]
	at com.espertech.esper.core.service.EPRuntimeImpl.sendEvent(EPRuntimeImpl.java:286) [esper-5.2.0.jar:na]
	at EsperBreaker.main(EsperBreaker.java:34) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:na]
```
But if you substitute internals of the expression for its invocation, then everything go OK.

**Comment by bernhardttom** [comment]
merged into master for 5.4 release
