### ISSUE TITLE
Expression with bracket-syntax table access causes string constant validation exception

### ISSUE THREAD

**Issue by dmekhanikov** [espertechinc/esper#31]
Test class:
```java
import com.espertech.esper.client.EPServiceProvider;
import com.espertech.esper.client.EPServiceProviderManager;
import com.espertech.esper.client.deploy.DeploymentException;
import com.espertech.esper.client.deploy.Module;
import com.espertech.esper.client.deploy.ParseException;

import java.io.IOException;

public class EsperBreaker {
    public static void main(String ... args) throws ParseException, DeploymentException, IOException {
        EPServiceProvider epService = EPServiceProviderManager.getDefaultProvider();

        Module module = epService.getEPAdministrator().getDeploymentAdmin().parse("" +
                "create schema OrderIssue(id int, instrumentId int);\n" +
                "create window Positions.win:keepall() as (id int, instrumentId int, instrumentName string);\n" +
                "create table Instruments(id int primary key, name string);\n" +
                "create expression getInstrumentName {o => Instruments[o.instrumentId].name};\n" +
                "on OrderIssue oi\n" +
                "insert into Positions(id, instrumentId, instrumentName)\n" +
                "    select id, instrumentId, getInstrumentName(oi);"
        );
        epService.getEPAdministrator().getDeploymentAdmin().deploy(module, null);
    }
}
```
Deployment error appears:
```
com.espertech.esper.epl.expression.core.ExprValidationException: Failed to validate select-clause expression 'getInstrumentName(oi)': Error validating expression declaration 'getInstrumentName': Failed to validate declared expression body expression 'Instruments["o.instrumentId"].name': Incompatible type returned by a key expression for use with table 'Instruments', the key expression '"o.instrumentId"' returns 'java.lang.String' but the table expects 'java.lang.Integer'
	at com.espertech.esper.epl.expression.core.ExprNodeUtility.getValidatedSubtree(ExprNodeUtility.java:306) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.epl.core.ResultSetProcessorFactoryFactory.validateSelectAssignColNames(ResultSetProcessorFactoryFactory.java:773) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.epl.core.ResultSetProcessorFactoryFactory.getProcessorPrototype(ResultSetProcessorFactoryFactory.java:133) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.core.start.EPStatementStartMethodOnTrigger.handleContextFactorySplitStream(EPStatementStartMethodOnTrigger.java:353) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.core.start.EPStatementStartMethodOnTrigger.startInternal(EPStatementStartMethodOnTrigger.java:140) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.core.start.EPStatementStartMethodBase.start(EPStatementStartMethodBase.java:57) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.core.service.StatementLifecycleSvcImpl.startInternal(StatementLifecycleSvcImpl.java:692) [esper-5.2.0.jar:na]
	at com.espertech.esper.core.service.StatementLifecycleSvcImpl.start(StatementLifecycleSvcImpl.java:654) [esper-5.2.0.jar:na]
	at com.espertech.esper.core.service.StatementLifecycleSvcImpl.createAndStart(StatementLifecycleSvcImpl.java:151) [esper-5.2.0.jar:na]
	at com.espertech.esper.core.service.EPAdministratorImpl.createEPLStmt(EPAdministratorImpl.java:117) [esper-5.2.0.jar:na]
	at com.espertech.esper.core.service.EPAdministratorImpl.createEPL(EPAdministratorImpl.java:91) [esper-5.2.0.jar:na]
	at com.espertech.esper.core.deploy.EPDeploymentAdminImpl.deployInternal(EPDeploymentAdminImpl.java:174) [esper-5.2.0.jar:na]
	at com.espertech.esper.core.deploy.EPDeploymentAdminImpl.deploy(EPDeploymentAdminImpl.java:102) [esper-5.2.0.jar:na]
	at EsperBreaker.main(EsperBreaker.java:23) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:na]
Caused by: com.espertech.esper.epl.expression.core.ExprValidationException: Error validating expression declaration 'getInstrumentName': Failed to validate declared expression body expression 'Instruments["o.instrumentId"].name': Incompatible type returned by a key expression for use with table 'Instruments', the key expression '"o.instrumentId"' returns 'java.lang.String' but the table expects 'java.lang.Integer'
	at com.espertech.esper.epl.declexpr.ExprDeclaredNodeImpl.validate(ExprDeclaredNodeImpl.java:203) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.epl.expression.core.ExprNodeUtility.getValidatedSubtreeInternal(ExprNodeUtility.java:374) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.epl.expression.core.ExprNodeUtility.getValidatedSubtree(ExprNodeUtility.java:289) ~[esper-5.2.0.jar:na]
	... 18 common frames omitted
Caused by: com.espertech.esper.epl.expression.core.ExprValidationException: Failed to validate declared expression body expression 'Instruments["o.instrumentId"].name': Incompatible type returned by a key expression for use with table 'Instruments', the key expression '"o.instrumentId"' returns 'java.lang.String' but the table expects 'java.lang.Integer'
	at com.espertech.esper.epl.expression.core.ExprNodeUtility.getValidatedSubtree(ExprNodeUtility.java:306) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.epl.declexpr.ExprDeclaredNodeImpl.validate(ExprDeclaredNodeImpl.java:199) ~[esper-5.2.0.jar:na]
	... 20 common frames omitted
Caused by: com.espertech.esper.epl.expression.core.ExprValidationException: Incompatible type returned by a key expression for use with table 'Instruments', the key expression '"o.instrumentId"' returns 'java.lang.String' but the table expects 'java.lang.Integer'
	at com.espertech.esper.epl.expression.table.ExprTableNodeUtil.validateExpressions(ExprTableNodeUtil.java:44) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.epl.expression.table.ExprTableAccessNode.validateGroupKeys(ExprTableAccessNode.java:77) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.epl.expression.table.ExprTableAccessNodeSubprop.validateBindingInternal(ExprTableAccessNodeSubprop.java:51) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.epl.expression.table.ExprTableAccessNode.validate(ExprTableAccessNode.java:65) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.epl.expression.core.ExprNodeUtility.getValidatedSubtreeInternal(ExprNodeUtility.java:374) ~[esper-5.2.0.jar:na]
	at com.espertech.esper.epl.expression.core.ExprNodeUtility.getValidatedSubtree(ExprNodeUtility.java:289) ~[esper-5.2.0.jar:na]
	... 21 common frames omitted
```
I guess that now all fields accessed from expressions are supposed to be of String type. Type-checking of expressions should be performed for every usage or disabled at all.

**Comment by bernhardttom** [comment]
merged changes for this issue into master for 5.4 release
