### ISSUE TITLE
NullPointerException with non-aggregated `having` clause and addListenerWithReplay

### ISSUE THREAD

**Issue by mstrobel** [espertechinc/esper#33]
The following example illustrates a `NullPointerException` in `ResultSetProcessorSimpleTransform` when a query over a named window includes a simple `having` clause that initially yields no results:

```java
import com.espertech.esper.client.*;

import java.util.Arrays;

public class EsperBug {
    static class TestEvent {
        private final String _origin;
        private final int _size;

        public TestEvent(final String origin, final int size) {
            _origin = origin;
            _size = size;
        }

        public String getOrigin() {
            return _origin;
        }

        public int getSize() {
            return _size;
        }
    }

    public static void main(final String... args) throws Throwable {
        final EPServiceProvider epService = EPServiceProviderManager.getDefaultProvider();
        final EPRuntime runtime = epService.getEPRuntime();
        final EPAdministrator administrator = epService.getEPAdministrator();

        administrator.getConfiguration().addEventType("TestEvent", TestEvent.class);

        administrator.getDeploymentAdmin().parseDeploy(
            "create window TestEvents.win:keepall() as TestEvent;\n" +
            "insert into TestEvents select * from TestEvent;\n");

        runtime.sendEvent(new TestEvent("ORIGIN", 1));
        runtime.sendEvent(new TestEvent("ORIGIN", 2));

        final EPStatement epl = administrator.createEPL(
            "select origin, size from TestEvents\n" +
//            "group by origin\n" +
            "having size > 4000"
        );

        epl.start();

        epl.addListenerWithReplay(
            new UpdateListener() {
                @Override
                public void update(final EventBean[] newEvents, final EventBean[] oldEvents) {
                    System.out.println(Arrays.toString(newEvents));
                }
            }
        );
    }
}
```
The error stack trace is as follows:

    Exception in thread "main" java.lang.NullPointerException
        at com.espertech.esper.epl.core.ResultSetProcessorSimpleTransform.transform(ResultSetProcessorSimpleTransform.java:36)
        at com.espertech.esper.collection.TransformEventIterator.next(TransformEventIterator.java:48)
        at com.espertech.esper.collection.TransformEventIterator.next(TransformEventIterator.java:20)
        at com.espertech.esper.core.service.EPStatementImpl.addListenerWithReplay(EPStatementImpl.java:366)
        at EsperBug.main(EsperBug.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

The exception site, `ResultSetProcessorSimpleTransform::transform`, attempts to access an element in an array of `EventBean[]` that happens to be `null` in this case:

    public EventBean transform(EventBean theEvent)
    {
        newData[0] = theEvent;
        UniformPair<EventBean[]> pair = resultSetProcessor.processViewResult(newData, null, true);
        return pair.getFirst()[0];
    }

Adding a `group by` clause circumvents the exception, as can be seen by uncommenting the second line of the query.

**Comment by bernhardttom** [comment]
changed merged to master for 5.4 release
