### ISSUE TITLE
`mvn install` fails with "error: unmappable character for encoding UTF8"

### ISSUE THREAD

**Issue by gigafone** [espertechinc/esper#34]
I clone the repository and checkout master (currently the same as the 'release_5.3.0' tag).

When I run `mvn install -e -X` I get:

```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.3", arch: "x86_64", family: "mac"
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: javax.enterprise.util.* < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
```

(...I removed many intermediate lines...)

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.959 s
[INFO] Finished at: 2016-01-12T13:26:13-08:00
[INFO] Final Memory: 15M/437M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project esper: Compilation failure
[ERROR] /Groups/dev/src/github/espertechinc/esper/esper/src/main/java/com/espertech/esper/epl/approx/CountMinSketchStateHashes.java:[20,8] error: unmappable character for encoding UTF8
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project esper: Compilation failure
/Groups/dev/src/github/espertechinc/esper/esper/src/main/java/com/espertech/esper/epl/approx/CountMinSketchStateHashes.java:[20,8] error: unmappable character for encoding UTF8


	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
/Groups/dev/src/github/espertechinc/esper/esper/src/main/java/com/espertech/esper/epl/approx/CountMinSketchStateHashes.java:[20,8] error: unmappable character for encoding UTF8


	at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:516)
	at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:114)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by gigafone** [comment]
The cause was the phrase "Count–min sketch" which contains an [en dash; e.g. –](https://en.wikipedia.org/wiki/Dash). It looks like it was pasted into the code incorrectly, breaking UTF-8 encoding.

Here's a git patch:

```
diff --git a/esper/src/main/java/com/espertech/esper/epl/approx/CountMinSketchStateHashes.java b/esper/src/main/java/com/espertech/esper/epl/approx/Cou
index 7c62388..c5fc0cd 100644
--- a/esper/src/main/java/com/espertech/esper/epl/approx/CountMinSketchStateHashes.java
+++ b/esper/src/main/java/com/espertech/esper/epl/approx/CountMinSketchStateHashes.java
@@ -17,7 +17,7 @@ import java.util.Random;

 /**
  * <p>
- * Count<96>min sketch (or CM sketch) is a probabilistic sub-linear space streaming algorithm
+ * Count-min sketch (or CM sketch) is a probabilistic sub-linear space streaming algorithm
  * (source: Wikipedia, see http://en.wikipedia.org/wiki/Count%E2%80%93min_sketch)
  * </p>
  *
@@ -114,4 +114,3 @@ public class CountMinSketchStateHashes {
         return result;
     }
 }
-
```

**Comment by gigafone** [comment]
My commit to fix is here: https://github.com/gigafone/esper/commit/f9bb0be725dc75fe3242e94f4d9e5784df62fd35

**Comment by bernhardttom** [comment]
thanks, the change is incorporated
