### ISSUE TITLE
Problem signing application based on Esper due to CGLIB 3.1 dependency

### ISSUE THREAD

**Issue by andyflury** [espertechinc/esper#51]
When trying to sign an application that is using Esper the following exception is thrown:

`2016-07-12 17:13:48,674 WARN  [main] [com.espertech.esper.event.bean.BeanEventType] .initialize Unable to obtain CGLib fast class and/or method implementation for class ch.algotrader.service.MarketDataService, error msg is java.lang.reflect.InvocationTargetException-->null 
net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:237) ~[cglib-nodep-3.1.jar:?]
	at net.sf.cglib.reflect.FastClass$Generator.create(FastClass.java:64) ~[cglib-nodep-3.1.jar:?]
	at net.sf.cglib.reflect.FastClass.create(FastClass.java:46) ~[cglib-nodep-3.1.jar:?]
	at com.espertech.esper.event.bean.BeanEventType.initialize(BeanEventType.java:359) [esper-5.3.0.jar:?]
	at com.espertech.esper.event.bean.BeanEventType.<init>(BeanEventType.java:91) [esper-5.3.0.jar:?]
	at com.espertech.esper.event.bean.BeanEventAdapter.createBeanType(BeanEventAdapter.java:142) [esper-5.3.0.jar:?]
	at com.espertech.esper.event.EventAdapterServiceImpl.addBeanType(EventAdapterServiceImpl.java:360) [esper-5.3.0.jar:?]
	at com.espertech.esper.epl.variable.VariableServiceImpl.createNewVariable(VariableServiceImpl.java:296) [esper-5.3.0.jar:?]
	at com.espertech.esper.core.service.EPServicesContextFactoryDefault.initVariables(EPServicesContextFactoryDefault.java:300) [esper-5.3.0.jar:?]
	at com.espertech.esper.core.service.EPServicesContextFactoryDefault.createServicesContext(EPServicesContextFactoryDefault.java:141) [esper-5.3.0.jar:?]
	at com.espertech.esper.core.service.EPServiceProviderImpl.doInitialize(EPServiceProviderImpl.java:498) [esper-5.3.0.jar:?]
	at com.espertech.esper.core.service.EPServiceProviderImpl.<init>(EPServiceProviderImpl.java:91) [esper-5.3.0.jar:?]
	at com.espertech.esper.client.EPServiceProviderManager.getProviderInternal(EPServiceProviderManager.java:132) [esper-5.3.0.jar:?]
	at com.espertech.esper.client.EPServiceProviderManager.getProvider(EPServiceProviderManager.java:88) [esper-5.3.0.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:384) ~[cglib-nodep-3.1.jar:?]
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:219) ~[cglib-nodep-3.1.jar:?]
	... 124 more
Caused by: java.lang.SecurityException: class "ch.algotrader.service.MarketDataService$$FastClassByCGLIB$$f9bb9a92_2"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895) ~[?:1.8.0_66]
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665) ~[?:1.8.0_66]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758) ~[?:1.8.0_66]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:384) ~[cglib-nodep-3.1.jar:?]
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:219) ~[cglib-nodep-3.1.jar:?]
	... 124 more`

According to the https://github.com/cglib/cglib/commit/f9d2f6cef31615d2dd98b3d41ca7de4b6294f2a0 this was fixed in CGLIB 3.2.4

Esper currently depends on CGLIB 3.1. But manually adding a dependency to CGLIB 3.2.4 fixes the issue

**Comment by bernhardttom** [comment]
The CGLIB version will be updated at the time of release of the 6.0 version. This is because between minor versions we don't update dependent jar files.

**Comment by kingbase** [comment]
@andyflury Hello Andy. Could you tell me how to manually adding dependency?

I added the dependency in my sbt file like this:

```
libraryDependencies += "cglib" % "cglib" % "3.2.4"
libraryDependencies += "com.espertech" % "esper" % "7.1.0"
libraryDependencies += "com.espertech" % "esperio-csv" % "7.1.0"
```

but it doesn't work.
