### ISSUE TITLE
on-demand query null results exception with group by/having

### ISSUE THREAD

**Issue by amit5094** [espertechinc/esper#59]
We are using an on-demand query as below in one of our tables InstanceSymbolNetVal 
`select instanceId, sum(Math.abs(isnv.aggNetVal)) as exposure  from InstanceSymbolNetVal isnv group by instanceId  having sum(Math.abs(isnv.aggNetVal)) > ?";
`
```
    private static void printTables(EPRuntime runtime) {
        String tableQuery = "select instanceId, sum(Math.abs(isnv.aggNetVal)) as exposure  from InstanceSymbolNetVal isnv group by instanceId  having sum(Math.abs(isnv.aggNetVal)) > ?";
        EPOnDemandPreparedQueryParameterized query = runtime.prepareQueryWithParameters(tableQuery);
        query.setObject(1, 2000);
        EPOnDemandQueryResult result = runtime.executeQuery(query);
        for (EventBean bean : result.getArray()) {
            System.out.println("Table data -> Iid: " + bean.get("instanceId") + bean.get("exposure"));
        }
    }

```
if the above query does not return any results we can see below exception thrown by Esper. I have debugged this part have noticed that at line (EPPreparedExecuteMethodQuery.java:354) the results object is null. We do not see any such behaviour if the group by clause is missing.

Exception in thread "main" com.espertech.esper.client.EPStatementException: Error executing statement: null
	at com.espertech.esper.core.service.EPRuntimeImpl.executeQueryInternal(EPRuntimeImpl.java:1565)
	at com.espertech.esper.core.service.EPRuntimeImpl.executeQuery(EPRuntimeImpl.java:1542)
	at amit.esper.EsperPOCDemandQueryAbs.printTables(EsperPOCDemandQueryAbs.java:102)
	at amit.esper.EsperPOCDemandQueryAbs.main(EsperPOCDemandQueryAbs.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.NullPointerException
	at com.espertech.esper.core.start.EPPreparedExecuteMethodQuery.process(EPPreparedExecuteMethodQuery.java:354)
	at com.espertech.esper.core.start.EPPreparedExecuteMethodQuery.execute(EPPreparedExecuteMethodQuery.java:215)
	at com.espertech.esper.core.service.EPRuntimeImpl.executeQueryInternal(EPRuntimeImpl.java:1554)
	... 8 more

**Comment by bernhardttom** [comment]
Provide the test class please.

**Comment by bernhardttom** [comment]
Works according to below test code
`
`    
public void testIt() throws Exception {
        EPServiceProvider epService = EPServiceProviderManager.getDefaultProvider();
        String epl =
                "create schema Event(instanceId string, aggNetVal double);\n" +
                "create window InstanceSymbolNetVal#keepall as Event;\n";
        epService.getEPAdministrator().getDeploymentAdmin().parseDeploy(epl);

        String tableQuery = "select instanceId, sum(Math.abs(isnv.aggNetVal)) as exposure  from InstanceSymbolNetVal isnv group by instanceId  having sum(Math.abs(isnv.aggNetVal)) > ?";
        EPOnDemandPreparedQueryParameterized query = epService.getEPRuntime().prepareQueryWithParameters(tableQuery);
        query.setObject(1, 2000);
        EPOnDemandQueryResult result = epService.getEPRuntime().executeQuery(query);
        for (EventBean bean : result.getArray()) {
            System.out.println("Table data -> Iid: " + bean.get("instanceId") + bean.get("exposure"));
        }
    }
}`
`
