### ISSUE TITLE
IllegalArgumentException when undeploying module using context variables

### ISSUE THREAD

**Issue by unhit** [espertechinc/esper#62]
Exception is thrown when undeploying module using context variable. I believe problem is related to `RPK-972-99663 create-variable with context not releasing variable on undeploy with deployment admin` and occurs since 5.3.0.

```
2016-12-16 13:15:34.541 [INFO] com.espertech.esper.core.service.EPServiceProviderImpl [main] [EPServiceProviderImpl:415] Initializing engine URI 'default' version 5.5.0
2016-12-16 13:15:35.305 [WARN] com.espertech.esper.core.service.ExceptionHandlingService [main] [ExceptionHandlingService:77] Exception encountered performing instance stop for statement 'stmt_2' expression 'context test create variable int testvar' : Failed to find variable 'testvar'
java.lang.IllegalArgumentException: Failed to find variable 'testvar'
	at com.espertech.esper.epl.variable.VariableServiceImpl.deallocateVariableState(VariableServiceImpl.java:420)
	at com.espertech.esper.core.context.factory.StatementAgentInstanceFactoryCreateVariable$1.stop(StatementAgentInstanceFactoryCreateVariable.java:58)
	at com.espertech.esper.core.context.util.StatementAgentInstanceUtil.stopSafe(StatementAgentInstanceUtil.java:94)
	at com.espertech.esper.core.context.util.StatementAgentInstanceUtil.stop(StatementAgentInstanceUtil.java:113)
	at com.espertech.esper.core.context.util.StatementAgentInstanceUtil.stopAgentInstanceRemoveResources(StatementAgentInstanceUtil.java:77)
	at com.espertech.esper.core.context.util.StatementAgentInstanceUtil.stopAgentInstances(StatementAgentInstanceUtil.java:69)
	at com.espertech.esper.core.context.mgr.ContextManagerImpl.safeDestroy(ContextManagerImpl.java:127)
	at com.espertech.esper.core.context.mgr.ContextManagerImpl.destroyStatement(ContextManagerImpl.java:114)
	at com.espertech.esper.core.context.mgr.ContextManagementServiceImpl.destroyedStatement(ContextManagementServiceImpl.java:91)
	at com.espertech.esper.core.start.EPStatementStartMethodCreateVariable$3.destroy(EPStatementStartMethodCreateVariable.java:109)
	at com.espertech.esper.core.start.EPStatementDestroyCallbackList.destroy(EPStatementDestroyCallbackList.java:40)
	at com.espertech.esper.core.service.StatementLifecycleSvcImpl.destroyInternal(StatementLifecycleSvcImpl.java:1598)
	at com.espertech.esper.core.service.StatementLifecycleSvcImpl.destroy(StatementLifecycleSvcImpl.java:862)
	at com.espertech.esper.core.service.EPStatementImpl.destroy(EPStatementImpl.java:149)
	at com.espertech.esper.core.deploy.EPDeploymentAdminImpl.undeployRemoveInternal(EPDeploymentAdminImpl.java:595)
	at com.espertech.esper.core.deploy.EPDeploymentAdminImpl.undeployRemoveInternal(EPDeploymentAdminImpl.java:546)
	at com.espertech.esper.core.deploy.EPDeploymentAdminImpl.undeployRemove(EPDeploymentAdminImpl.java:280)
	at x.x.x.x.ContextVariableTest.shouldNotThrowExceptionWhenDestroyingContextVariable(ContextVariableTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

Here is the test class:
```
public class ContextVariableTest {

    @Test
    public void shouldNotThrowExceptionWhenDestroyingContextVariable() throws IOException, ParseException, DeploymentException {
        // given
        Configuration config = new Configuration();
        config.addEventType("TestEvent", TestEvent.class);
        EPServiceProvider epService = EPServiceProviderManager.getDefaultProvider(config);
        EPRuntime epRuntime = epService.getEPRuntime();
        EPAdministrator epAdmin = epService.getEPAdministrator();
        EPDeploymentAdmin epDeployAdmin = epAdmin.getDeploymentAdmin();
        DeploymentResult result = epDeployAdmin
                .parseDeploy("module test; create context test partition by id from TestEvent; context test create variable int testvar; context test on TestEvent e set testvar = e.id;");
        epRuntime.sendEvent(new TestEvent());
        epDeployAdmin.undeployRemove(result.getDeploymentId());
    }

    public static class TestEvent {
        private int id;

        public int getId() {
            return id;
        }

        public void setId(int id) {
            this.id = id;
        }
    }
}
```

**Comment by bernhardttom** [comment]
merged
