### ISSUE TITLE
NPE when trying to use the HTTP input adapter with schema-provided XML events

### ISSUE THREAD

**Issue by ysmartin** [espertechinc/esper#73]
When trying to through the HTTP input adaptor, **(using Esper 5.5.0)**, events which have been defined in an XSD (plus proper configuration), I get the following error
```
21:46:12,822 ERROR [EsperHttpRequestHandler] Error processing Http GET request target '/myendpoint?stream=Reading&param1=A&param2=LEFT&param3=&param4=
	at com.espertech.esperio.http.EsperHttpRequestHandler.makeCacheEntry(EsperHttpRequestHandler.java:103)
	at com.espertech.esperio.http.EsperHttpRequestHandler.handle(EsperHttpRequestHandler.java:63)
	at com.espertech.esperio.http.EsperHttpRequestHandler.handle(EsperHttpRequestHandler.java:50)
	at org.apache.http.protocol.HttpService.doService(HttpService.java:423)
	at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:341)
	at com.espertech.esperio.http.core.WorkerThread.run(WorkerThread.java:37)
```
(the parameter names in the URL query have been simplified)

After debugging and tracking it down, I understand that XML events cannot be used with this adapter, can they?
In particular the ```makeCacheEntry``` method tries to get writeable properties of the ```EventType```, which is eventually resolved by ```EventAdapterServiceHelper.getWriteableProperties(EventType eventType, boolean allowAnyType)```: as the ```EventType``` it receives is a ```SchemaXMLEventType```, which does not extend from either ```BeanEventType``` or ```BaseNestableEventType```, it returns null, and thus the NPE.
Is this a bug or a feature? In the second case, I suggest that the documentation be amended.

**Comment by bernhardttom** [comment]
XML events are backed by DOM and so can't be created. The doc needs an update.
