### ISSUE TITLE
Inheritance of avro events fails unpredictably

### ISSUE THREAD

**Issue by ysmartin** [espertechinc/esper#76]
According to the [documentation](http://www.espertech.com/esper/release-6.0.1/esper-reference/html/appendix_eventrepavro.html#appendix_eventrepavro_overview), 
> A given Avro event type can have only a single supertype that must also be an Avro event type.

However, this behaviour does not always hold.
In particular, if I try to define avro events through an Esper configuration file, I get a ConfigurationException  caused in turn by this EventAdapterException:

```
Caused by: com.espertech.esper.event.EventAdapterException: Supertype by name 'SampleParentEvent' could not be found
	at com.espertech.esper.event.EventTypeUtility.getSuperTypesDepthFirst(EventTypeUtility.java:70)
	at com.espertech.esper.event.EventTypeUtility.getSuperTypesDepthFirst(EventTypeUtility.java:54)
	at com.espertech.esper.event.EventAdapterServiceImpl.addAvroType(EventAdapterServiceImpl.java:813)
	at com.espertech.esper.core.service.EPServicesContextFactoryDefault.init(EPServicesContextFactoryDefault.java:373)
	... 8 more
```
Attached you may find a minimal test case which triggers the exception. It happens that, if I comment the third event definition (SampleProducerEvent), which is completely unrelated to both the parent and the child, it seems to work properly.

[test_config.xml.txt](https://github.com/espertechinc/esper/files/1035979/test_config.xml.txt)

**Comment by ysmartin** [comment]
My two cents after debugging, see stack trace with comments inline:

```
Caused by: com.espertech.esper.event.EventAdapterException: Supertype by name 'SampleParentEvent' could not be found
	at com.espertech.esper.event.EventTypeUtility.getSuperTypesDepthFirst(EventTypeUtility.java:70)
            > It is not found because there is no entry in the Map<String, ? extends EventType> nameToTypeMap under the supertype event name...

	at com.espertech.esper.event.EventTypeUtility.getSuperTypesDepthFirst(EventTypeUtility.java:54)
	at com.espertech.esper.event.EventAdapterServiceImpl.addAvroType(EventAdapterServiceImpl.java:813)
            > Indeed, the nameToTypeMap (which is an attribute of this EventAdapterServiceImpl) is empty. Why? What has happened to the first event we had defined in our config file?

	at com.espertech.esper.core.service.EPServicesContextFactoryDefault.init(EPServicesContextFactoryDefault.java:373)
            > Answer: it seems that the second event type (from the config file) is being processed before the first one. avroNames contains both event types, but in reversed order. Thus, addAvroType is invoked for the child event type before the parent.

	... 8 more
```

After tracking down the culprit, it seems to be hidden at `EPServiceProviderImpl.takeSnapshot:692`, where `avroSchemas` is created as a `HashMap`, which does not guarantee the order originally provided by the `LinkedHashMap configuration.eventTypesAvro`. Then the contents of avroSchemas are poured in a random order onto copy.eventTypesAvro, which is returned by the method. This instance of `ConfigurationInformation` is eventually used as `configSnapshot` by the method `EPServicesContextFactoryDefault.init`, which travels the map in a "wrong" order.

**Comment by bernhardttom** [comment]
The workaround is to add the using "epService.getEPAdministrator().getConfiguration().add..."
