### ISSUE TITLE
NullPointerException cause by com.espertech.esper.core.start.EPPreparedExecuteMethodQuery.process

### ISSUE THREAD

**Issue by homepy** [espertechinc/esper#80]
Version 5.4.0

```
// Declere a event 'Param'
Map<String, Object> eventDef = new HashMap<>();
eventDef.put("name", String.class);
eventDef.put("column1", String.class);
eventDef.put("column2", String.class);
eventDef.put("column3", String.class);
eventDef.put("column4", String.class);
eventDef.put("column5", String.class);
this.admin.getConfiguration().addEventType("Param", eventDef);
 

// create window 'ParamWindow' and index
String eplCreateWindow = "create window ParamWindow.win:keepall() as select * from Param ";
String eplCreateIndex = " create index ParamIndex on ParamWindow(name) "; 

....
EPOnDemandPreparedQueryParameterized prepared = runtime.prepareQueryWithParameters("select cast( count(1), string) as flag  from ParamWindow p1,  ParamWindow p2 where (?).length() >=7 and (?).substring(4, 7) <> '000' and p1.name = (?).substring(4, 7) and (?).length()>=2 and p2.name.endsWith('Z') and p2.name.startsWith( (?).substring(0, 2) ) and p1.column1 = p2.column1 ");
prepared.setObject()
....
EPOnDemandQueryResult result = runtime.executeQuery(prepared);
```

When excute the EPOnDemandQuery, it thorws a NullPointerException.

```
com.espertech.esper.client.EPStatementException: Error executing statement: null
at com.espertech.esper.core.service.EPRuntimeImpl.executeQueryInternal(EPRuntimeImpl.java:1565) ~[esper-5.4.0.jar:?]
at com.espertech.esper.core.service.EPRuntimeImpl.executeQuery(EPRuntimeImpl.java:1542) ~[esper-5.4.0.jar:?]
...
Caused by: java.lang.NullPointerException
at com.espertech.esper.epl.core.ResultSetProcessorUtil.applyAggJoinResult(ResultSetProcessorUtil.java:53) ~[esper-5.4.0.jar:?]
at com.espertech.esper.epl.core.ResultSetProcessorRowForAll.processJoinResult(ResultSetProcessorRowForAll.java:87) ~[esper-5.4.0.jar:?]
at com.espertech.esper.core.start.EPPreparedExecuteMethodQuery.process(EPPreparedExecuteMethodQuery.java:346) ~[esper-5.4.0.jar:?]
at com.espertech.esper.core.start.EPPreparedExecuteMethodQuery.execute(EPPreparedExecuteMethodQuery.java:215) ~[esper-5.4.0.jar:?]
at com.espertech.esper.core.service.EPRuntimeImpl.executeQueryInternal(EPRuntimeImpl.java:1554) ~[esper-5.4.0.jar:?]
... 13 more
```

[com.espertech.esper.core.start.EPPreparedExecuteMethodQuery.process(EPPreparedExecuteMethodQuery.java:346) ] ,(https://github.com/espertechinc/esper/blob/release_5.4.0/esper/src/main/java/com/espertech/esper/core/start/EPPreparedExecuteMethodQuery.java)
the second argument of "results = resultSetProcessor.processJoinResult(result.getFirst(), null, true);"
is null, which cause this Exception.

**Comment by bernhardttom** [comment]
Thanks, this change is made.
