### ISSUE TITLE
NPE when selecting last/first on a property used to partition the context

### ISSUE THREAD

**Issue by dm3** [espertechinc/esper#81]
Using Esper 6.0.1 The following statement fails with an NPE after sending at least one event and advancing the clock so that the batch triggers:

```
create schema Input (key string, value string);

create context ByKey
partition by key from Input;

context ByKey
select last(i.key)
from Input#time_batch(1 minute) as i;
```

Exception:

```
java.lang.NullPointerException: null
        at com.espertech.esper.epl.expression.core.ExprIdentNodeEvaluatorContext.evaluate(ExprIdentNodeEvaluatorContext.java:37)
        at com.espertech.esper.epl.agg.access.AggregationAccessorLastWEval.getValue(AggregationAccessorLastWEval.java:46)
        at com.espertech.esper.epl.agg.service.AggSvcGroupAllAccessOnlyImpl.getValue(AggSvcGroupAllAccessOnlyImpl.java:77)
        at com.espertech.esper.core.context.stmt.AIRegistryAggregationMultiPerm.getValue(AIRegistryAggregationMultiPerm.java:68)
        at com.espertech.esper.epl.expression.baseagg.ExprAggregateNodeBase.evaluate(ExprAggregateNodeBase.java:150)
        at com.espertech.esper.epl.core.eval.EvalSelectNoWildcardMap.process(EvalSelectNoWildcardMap.java:41)
        at com.espertech.esper.epl.core.SelectExprResultProcessor.process(SelectExprResultProcessor.java:58)
        at com.espertech.esper.epl.core.ResultSetProcessorRowForAll.getSelectListEvents(ResultSetProcessorRowForAll.java:148)
        at com.espertech.esper.epl.core.ResultSetProcessorRowForAll.processViewResult(ResultSetProcessorRowForAll.java:116)
        at com.espertech.esper.epl.view.OutputProcessViewDirect.update(OutputProcessViewDirect.java:67)
        at com.espertech.esper.view.ViewSupport.updateChildren(ViewSupport.java:106)
        at com.espertech.esper.view.window.TimeBatchView.sendBatch(TimeBatchView.java:211)
        at com.espertech.esper.view.window.TimeBatchView$1.scheduledTrigger(TimeBatchView.java:271)
        at com.espertech.esper.core.service.EPRuntimeImpl.processStatementScheduleSingle(EPRuntimeImpl.java:1048)
        at com.espertech.esper.core.service.EPRuntimeImpl.processScheduleHandles(EPRuntimeImpl.java:671)
        at com.espertech.esper.core.service.EPRuntimeImpl.processSchedule(EPRuntimeImpl.java:630)
        at com.espertech.esper.core.service.EPRuntimeImpl.processTimeEvent(EPRuntimeImpl.java:535)
        at com.espertech.esper.core.service.EPRuntimeImpl.processEvent(EPRuntimeImpl.java:430)
        at com.espertech.esper.core.service.EPRuntimeImpl.sendEvent(EPRuntimeImpl.java:222)
```

If you remove the `context` or change `last(i.key)` to `last(i.value)` - the statement works correctly.

**Comment by bernhardttom** [comment]
cannot reproduce, no test provided
