### ISSUE TITLE
StackOverflowError originating from EPRuntimeImpl

### ISSUE THREAD

**Issue by eirikur-as** [espertechinc/esper#87]
I encountered the following error with esper 6.1.0. Unfortunately, I've not been able to reproduce the issue. There were 39 EPL statements active when this happened and I don't know which one triggered the error.

Regardless, the stack trace indicates that an infinite call-cycle can form between the `processStatementFilterSingle` and `handleFilterFault` methods in `EPRuntimeImpl`.

```
ERROR InboundUnitSendEvent:41  : Unexpected error processing unwrapped event: null 
java.lang.StackOverflowError: null
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.get(HashMap.java:556)
	at com.espertech.esper.filter.FilterParamIndexEqualsBase.get(FilterParamIndexEqualsBase.java:33)
	at com.espertech.esper.filter.IndexTreeBuilder.removeFromIndex(IndexTreeBuilder.java:234)
	at com.espertech.esper.filter.IndexTreeBuilder.removeFromIndex(IndexTreeBuilder.java:272)
	at com.espertech.esper.filter.IndexTreeBuilder.removeFromNode(IndexTreeBuilder.java:203)
	at com.espertech.esper.filter.IndexTreeBuilder.remove(IndexTreeBuilder.java:93)
	at com.espertech.esper.filter.EventTypeIndexBuilder.remove(EventTypeIndexBuilder.java:152)
	at com.espertech.esper.filter.FilterServiceBase.removeInternal(FilterServiceBase.java:70)
	at com.espertech.esper.filter.FilterServiceLockCoarse.remove(FilterServiceLockCoarse.java:83)
	at com.espertech.esper.core.context.activator.ViewableActivatorFilterProxyStopCallback.stop(ViewableActivatorFilterProxyStopCallback.java:31)
	at com.espertech.esper.core.context.util.StatementAgentInstanceUtil.stopSafe(StatementAgentInstanceUtil.java:93)
	at com.espertech.esper.core.context.util.StatementAgentInstanceUtil.stopSafe(StatementAgentInstanceUtil.java:87)
	at com.espertech.esper.core.context.util.StatementAgentInstanceUtil.stopSafe(StatementAgentInstanceUtil.java:82)
	at com.espertech.esper.core.context.util.StatementAgentInstanceUtil$1.stop(StatementAgentInstanceUtil.java:407)
	at com.espertech.esper.core.context.util.StatementAgentInstanceUtil.stopSafe(StatementAgentInstanceUtil.java:93)
	at com.espertech.esper.core.context.util.StatementAgentInstanceUtil.stop(StatementAgentInstanceUtil.java:113)
	at com.espertech.esper.core.context.util.StatementAgentInstanceUtil.stopAgentInstanceRemoveResources(StatementAgentInstanceUtil.java:76)
	at com.espertech.esper.core.context.util.StatementAgentInstanceUtil.stopAgentInstances(StatementAgentInstanceUtil.java:68)
	at com.espertech.esper.core.context.mgr.ContextManagerImpl.contextPartitionTerminate(ContextManagerImpl.java:186)
	at com.espertech.esper.core.context.mgr.ContextControllerInitTerm.rangeNotification(ContextControllerInitTerm.java:201)
	at com.espertech.esper.core.context.mgr.ContextControllerConditionPattern.matchFound(ContextControllerConditionPattern.java:98)
	at com.espertech.esper.core.context.mgr.ContextControllerConditionPattern$ConditionPatternMatchCallback.matchFound(ContextControllerConditionPattern.java:136)
	at com.espertech.esper.pattern.EvalRootStateNode.evaluateTrue(EvalRootStateNode.java:108)
	at com.espertech.esper.pattern.EvalFilterStateNode.evaluateTrue(EvalFilterStateNode.java:87)
	at com.espertech.esper.pattern.EvalFilterStateNode.matchFound(EvalFilterStateNode.java:136)
	at com.espertech.esper.core.service.EPRuntimeImpl.processStatementFilterSingle(EPRuntimeImpl.java:1142)
	at com.espertech.esper.core.service.EPRuntimeImpl.handleFilterFault(EPRuntimeImpl.java:1200)
	at com.espertech.esper.core.service.EPRuntimeImpl.processStatementFilterSingle(EPRuntimeImpl.java:1139)
	at com.espertech.esper.core.service.EPRuntimeImpl.handleFilterFault(EPRuntimeImpl.java:1200)
	at com.espertech.esper.core.service.EPRuntimeImpl.processStatementFilterSingle(EPRuntimeImpl.java:1139)
...etc
```

**Comment by eirikur-as** [comment]
Seeing as this is a StackOverFlowError, the full stacktrace is very long. I trimmed it to the point where the repetition begins. There's no useful information in the rest of the stacktrace since it consists solely of the following two entries, repeated until stackspace is exhausted.
```
	at com.espertech.esper.core.service.EPRuntimeImpl.handleFilterFault(EPRuntimeImpl.java:1200)
	at com.espertech.esper.core.service.EPRuntimeImpl.processStatementFilterSingle(EPRuntimeImpl.java:1139)
```
